# Generated by Django 5.1.15 on 2026-09-23 19:51

import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("masterdata", "0001_initial"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusEvent",
            fields=[
                ("seq", models.BigAutoField(primary_key=True, serialize=False)),
                ("at", models.DateTimeField()),
                ("unit_id", models.UUIDField(db_index=True)),
                ("txn_type", models.CharField(max_length=12)),
                ("from_state", models.CharField(max_length=24)),
                ("to_state", models.CharField(max_length=24)),
                ("actor_type", models.CharField(max_length=20)),
                ("actor_org_id", models.UUIDField(blank=True, null=True)),
                ("actor_user_id", models.UUIDField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("prev_hash", models.CharField(max_length=64)),
                ("hash", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="StatusConfirmation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "txn_type",
                    models.CharField(
                        choices=[
                            ("RENT", "Rent"),
                            ("SALE_NEW", "Sale New"),
                            ("SALE_RESALE", "Sale Resale"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "requested_state",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("AVAILABLE", "Available"),
                            ("AVAILABLE_UNCONFIRMED", "Available Unconfirmed"),
                            ("ON_HOLD", "On Hold"),
                            ("LET", "Let"),
                            ("SOLD", "Sold"),
                            ("OFF_MARKET", "Off Market"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "previous_state",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("AVAILABLE", "Available"),
                            ("AVAILABLE_UNCONFIRMED", "Available Unconfirmed"),
                            ("ON_HOLD", "On Hold"),
                            ("LET", "Let"),
                            ("SOLD", "Sold"),
                            ("OFF_MARKET", "Off Market"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("available_from", "Available From"),
                        ],
                        max_length=16,
                    ),
                ),
                ("response_date", models.DateField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("channel", models.CharField(default="whatsapp", max_length=12)),
                (
                    "link",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="common.sharelink",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by_org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orgs.brokerorg",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="masterdata.unit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StatusReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "txn_type",
                    models.CharField(
                        choices=[
                            ("RENT", "Rent"),
                            ("SALE_NEW", "Sale New"),
                            ("SALE_RESALE", "Sale Resale"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "reported_state",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("AVAILABLE", "Available"),
                            ("AVAILABLE_UNCONFIRMED", "Available Unconfirmed"),
                            ("ON_HOLD", "On Hold"),
                            ("LET", "Let"),
                            ("SOLD", "Sold"),
                            ("OFF_MARKET", "Off Market"),
                        ],
                        max_length=24,
                    ),
                ),
                ("actor_type", models.CharField(max_length=20)),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orgs.brokerorg",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="masterdata.unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["unit", "txn_type", "reported_state", "created_at"],
                        name="status_stat_unit_id_56c470_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UnitStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "txn_type",
                    models.CharField(
                        choices=[
                            ("RENT", "Rent"),
                            ("SALE_NEW", "Sale New"),
                            ("SALE_RESALE", "Sale Resale"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("AVAILABLE", "Available"),
                            ("AVAILABLE_UNCONFIRMED", "Available Unconfirmed"),
                            ("ON_HOLD", "On Hold"),
                            ("LET", "Let"),
                            ("SOLD", "Sold"),
                            ("OFF_MARKET", "Off Market"),
                        ],
                        default="UNKNOWN",
                        max_length=24,
                    ),
                ),
                ("since", models.DateTimeField()),
                ("last_confirmed_at", models.DateTimeField()),
                ("source_type", models.CharField(max_length=20)),
                ("confirmed_by_owner", models.BooleanField(default=False)),
                ("available_from", models.DateField(blank=True, null=True)),
                ("licence_end_date", models.DateField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "hold_org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orgs.brokerorg",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="masterdata.unit",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["state", "txn_type"],
                        name="status_unit_state_241664_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("unit", "txn_type"), name="uniq_unit_status"
                    )
                ],
            },
        ),
    ]
