# Generated by Django 5.2.7 on 2026-02-18 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(max_length=100)),
                ('context_id', models.UUIDField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['context_type', 'context_id'], name='communicati_context_8c12d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunicationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('role', models.CharField(max_length=100)),
                ('society_id', models.UUIDField()),
                ('active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='communicati_user_id_7e803e_idx'), models.Index(fields=['society_id'], name='communicati_society_182365_idx'), models.Index(fields=['role'], name='communicati_role_fd8075_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunicationScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('society_id', models.UUIDField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['society_id'], name='communicati_society_5b7812_idx'), models.Index(fields=['name'], name='communicati_name_8bc863_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunicationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('governed', models.BooleanField(default=True)),
                ('moderated', models.BooleanField(default=True)),
                ('audited', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.communicationscope')),
            ],
            options={
                'unique_together': {('name', 'scope')},
            },
        ),
        migrations.CreateModel(
            name='CommunicationThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('society_id', models.UUIDField()),
                ('locked', models.BooleanField(default=False)),
                ('governed', models.BooleanField(default=True)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.communicationchannel')),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.communicationcontext')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_type', models.CharField(default='text', max_length=50)),
                ('moderated', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('compliance_checked', models.BooleanField(default=False)),
                ('governance_decision', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.communicationparticipant')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.communicationthread')),
            ],
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['society_id'], name='communicati_society_ee382e_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['created_by'], name='communicati_created_9e7cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationmessage',
            index=models.Index(fields=['created_at'], name='communicati_created_3847e5_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationmessage',
            index=models.Index(fields=['moderated'], name='communicati_moderat_c449a6_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationmessage',
            index=models.Index(fields=['blocked'], name='communicati_blocked_06df61_idx'),
        ),
    ]
