# Generated by Django 5.1.15 on 2026-09-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerorg',
            name='accepting_enquiries',
            field=models.BooleanField(default=True),
        ),
    ]
