# Generated by Django 5.1.15 on 2026-09-25 06:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_accepting_enquiries'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
    ]
