# Generated by Django 5.1.15 on 2026-09-25 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_flat_register'),
        ('orgs', '0003_membership_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerorg',
            name='company_reg_no',
            field=models.CharField(blank=True, help_text='CIN / LLPIN / partnership registration', max_length=21),
        ),
        migrations.AddField(
            model_name='brokerorg',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='brokerorg',
            name='declared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokerorg',
            name='established_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokerorg',
            name='gst_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brokerorg',
            name='gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='brokerorg',
            name='legal_name',
            field=models.CharField(blank=True, help_text='As on PAN / GST', max_length=200),
        ),
        migrations.AddField(
            model_name='brokerorg',
            name='office_address_2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='brokerorg',
            name='office_city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='brokerorg',
            name='office_locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masterdata.locality'),
        ),
        migrations.AddField(
            model_name='brokerorg',
            name='office_pincode',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='brokerorg',
            name='office_state',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='brokerorg',
            name='owners',
            field=models.JSONField(blank=True, default=list, help_text='[{"name": .., "role": ..}] proprietor, partners or directors'),
        ),
        migrations.AddField(
            model_name='brokerorg',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual (no firm)'), ('proprietorship', 'Proprietorship'), ('partnership', 'Partnership firm'), ('llp', 'LLP'), ('private_limited', 'Private limited company'), ('public_limited', 'Public limited company')], max_length=20),
        ),
        migrations.AddField(
            model_name='brokerorg',
            name='pan_enc',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokerorg',
            name='pan_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='brokerorg',
            name='pan_masked',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='brokerorg',
            name='name',
            field=models.CharField(help_text='Trade name customers see', max_length=160),
        ),
    ]
