# Generated by Django 5.1.15 on 2026-09-23 19:51

import common.ids
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone_hash", models.CharField(max_length=64)),
                ("phone_enc", models.BinaryField()),
                ("name", models.CharField(blank=True, max_length=120)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("marketplace", "Marketplace"),
                            ("phone_call", "Phone Call"),
                            ("walk_in", "Walk In"),
                            ("referral", "Referral"),
                            ("board", "Board"),
                            ("whatsapp_group", "Whatsapp Group"),
                            ("import", "Import"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "consent_state",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("attested_verbal", "Attested Verbal"),
                            ("otp_confirmed", "Otp Confirmed"),
                            ("link_confirmed", "Link Confirmed"),
                            ("app", "App"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("consent_evidence", models.JSONField(blank=True, default=dict)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("visits_planned", "Visits Planned"),
                            ("shortlisted", "Shortlisted"),
                            ("negotiation", "Negotiation"),
                            ("closed_won", "Won"),
                            ("closed_lost", "Lost"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("lost_reason", models.CharField(blank=True, max_length=200)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("next_follow_up", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("call_in", "Call In"),
                            ("call_out", "Call Out"),
                            ("office_meeting", "Office Meeting"),
                            ("whatsapp", "Whatsapp"),
                            ("sms", "Sms"),
                            ("link_opened", "Link Opened"),
                            ("shortlist_response", "Shortlist Response"),
                            ("visit", "Visit"),
                            ("note", "Note"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("duration_s", models.PositiveIntegerField(blank=True, null=True)),
                ("summary", models.CharField(blank=True, max_length=500)),
                ("ref_type", models.CharField(blank=True, max_length=40)),
                ("ref_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("txn_type", models.CharField(max_length=12)),
                (
                    "property_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("bhk_min", models.DecimalField(decimal_places=1, max_digits=3)),
                ("bhk_max", models.DecimalField(decimal_places=1, max_digits=3)),
                ("budget_min", models.PositiveBigIntegerField(blank=True, null=True)),
                ("budget_max", models.PositiveBigIntegerField()),
                (
                    "search_area",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "max_station_distance_m",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "must_haves",
                    models.JSONField(
                        blank=True, default=dict, help_text="attr_key -> required value"
                    ),
                ),
                ("nice_to_haves", models.JSONField(blank=True, default=dict)),
                (
                    "house_rule_needs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='e.g. {"pets": "dog", "nonveg_cooking": true}',
                    ),
                ),
                ("move_in_by", models.DateField(blank=True, null=True)),
                ("occupants", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Shortlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=120)),
                ("shared_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShortlistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "customer_response",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("interested", "Interested"),
                            ("not_for_me", "Not For Me"),
                        ],
                        max_length=12,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
