# Generated by Django 5.1.15 on 2026-09-23 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0002_initial"),
        ("inventory", "0001_initial"),
        ("marketplace", "0001_initial"),
        ("masterdata", "0001_initial"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="org",
            field=models.ForeignKey(
                db_column="broker_org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="orgs.brokerorg",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="platform_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customerinteraction",
            name="by_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customerinteraction",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="crm.customer",
            ),
        ),
        migrations.AddField(
            model_name="customerinteraction",
            name="org",
            field=models.ForeignKey(
                db_column="broker_org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="orgs.brokerorg",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="crm.customer",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="enquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="marketplace.enquiry",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="localities",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="masterdata.locality"
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="org",
            field=models.ForeignKey(
                db_column="broker_org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="orgs.brokerorg",
            ),
        ),
        migrations.AddField(
            model_name="shortlist",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shortlists",
                to="crm.customer",
            ),
        ),
        migrations.AddField(
            model_name="shortlist",
            name="org",
            field=models.ForeignKey(
                db_column="broker_org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="orgs.brokerorg",
            ),
        ),
        migrations.AddField(
            model_name="shortlist",
            name="requirement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="crm.requirement",
            ),
        ),
        migrations.AddField(
            model_name="shortlistitem",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="inventory.listing",
            ),
        ),
        migrations.AddField(
            model_name="shortlistitem",
            name="org",
            field=models.ForeignKey(
                db_column="broker_org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="orgs.brokerorg",
            ),
        ),
        migrations.AddField(
            model_name="shortlistitem",
            name="shortlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="crm.shortlist",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("org", "phone_hash"), name="one_customer_per_phone_per_org"
            ),
        ),
    ]
