# Generated by Django 5.1.15 on 2026-09-24 11:54

import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.rls import enable_rls


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_row_level_security"),
        ("inventory", "0002_row_level_security"),
        ("masterdata", "0004_ownershipclaim_terms_alter_ownershipclaim_status"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="updates_muted",
            field=models.BooleanField(
                default=False,
                help_text="The customer turned off this broker's broadcast updates",
            ),
        ),
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("new_flat", "New Flat"),
                            ("price_drop", "Price Drop"),
                            ("news", "News"),
                        ],
                        max_length=12,
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("audience", models.JSONField(blank=True, default=dict)),
                ("recipients_total", models.PositiveIntegerField(default=0)),
                ("delivered_in_app", models.PositiveIntegerField(default=0)),
                ("not_on_app", models.PositiveIntegerField(default=0)),
                ("muted", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.listing",
                    ),
                ),
                (
                    "locality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="masterdata.locality",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        db_column="broker_org_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="orgs.brokerorg",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        enable_rls("crm_broadcast"),
    ]
