# Generated by Django 5.1.15 on 2026-09-23 19:51

import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("txn_type", models.CharField(max_length=12)),
                (
                    "asking_rent",
                    models.PositiveIntegerField(
                        blank=True, help_text="INR per month", null=True
                    ),
                ),
                (
                    "asking_price",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="INR", null=True
                    ),
                ),
                ("deposit", models.PositiveIntegerField(blank=True, null=True)),
                ("maintenance", models.PositiveIntegerField(blank=True, null=True)),
                ("negotiable", models.BooleanField(default=True)),
                ("available_from", models.DateField(blank=True, null=True)),
                ("brokerage_terms", models.CharField(blank=True, max_length=200)),
                ("owner_name", models.CharField(blank=True, max_length=120)),
                ("owner_phone_enc", models.BinaryField(blank=True, null=True)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("upload", "Upload"),
                            ("owner_invite", "Owner Invite"),
                            ("builder", "Builder"),
                        ],
                        default="manual",
                        max_length=14,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("publish_card", "Publish Card"),
                        ],
                        default="private",
                        max_length=14,
                    ),
                ),
                ("withdrawn_by_owner", models.BooleanField(default=False)),
                ("last_confirmed_at", models.DateTimeField()),
                ("private_notes", models.TextField(blank=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SavedColumnMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("header_signature", models.CharField(max_length=64)),
                ("mapping", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="UploadBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=200)),
                ("default_txn_type", models.CharField(default="RENT", max_length=12)),
                ("column_mapping", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("parsing", "Parsing"),
                            ("awaiting_review", "Awaiting Review"),
                            ("committed", "Committed"),
                            ("failed", "Failed"),
                        ],
                        default="parsing",
                        max_length=16,
                    ),
                ),
                ("counts", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UploadRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_no", models.PositiveIntegerField()),
                ("raw", models.JSONField()),
                ("parsed", models.JSONField(default=dict)),
                ("candidates", models.JSONField(default=list)),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("auto", "Auto"),
                            ("needs_confirmation", "Needs Confirmation"),
                            ("broker_confirmed", "Broker Confirmed"),
                            ("provisional", "Provisional"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                            ("committed", "Committed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("errors", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["row_no"],
            },
        ),
        migrations.CreateModel(
            name="KeyCustody",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "holder_type",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("office", "Office"),
                            ("staff", "Staff"),
                            ("society_office", "Society Office"),
                            ("lockbox", "Lockbox"),
                            ("neighbour", "Neighbour"),
                        ],
                        max_length=16,
                    ),
                ),
                ("instructions_enc", models.BinaryField(blank=True, null=True)),
                ("from_ts", models.DateTimeField(auto_now_add=True)),
                ("to_ts", models.DateTimeField(blank=True, null=True)),
                ("needs_handover", models.BooleanField(default=False)),
                (
                    "holder_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
