# Generated by Django 5.1.15 on 2026-09-23 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("masterdata", "0001_initial"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="keycustody",
            name="org",
            field=models.ForeignKey(
                db_column="broker_org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="orgs.brokerorg",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="org",
            field=models.ForeignKey(
                db_column="broker_org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="orgs.brokerorg",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="listings",
                to="masterdata.unit",
            ),
        ),
        migrations.AddField(
            model_name="keycustody",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keys",
                to="inventory.listing",
            ),
        ),
        migrations.AddField(
            model_name="savedcolumnmapping",
            name="org",
            field=models.ForeignKey(
                db_column="broker_org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="orgs.brokerorg",
            ),
        ),
        migrations.AddField(
            model_name="uploadbatch",
            name="micro_market",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="masterdata.micromarket",
            ),
        ),
        migrations.AddField(
            model_name="uploadbatch",
            name="org",
            field=models.ForeignKey(
                db_column="broker_org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="orgs.brokerorg",
            ),
        ),
        migrations.AddField(
            model_name="uploadbatch",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="uploadrow",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rows",
                to="inventory.uploadbatch",
            ),
        ),
        migrations.AddField(
            model_name="uploadrow",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="inventory.listing",
            ),
        ),
        migrations.AddField(
            model_name="uploadrow",
            name="org",
            field=models.ForeignKey(
                db_column="broker_org_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="orgs.brokerorg",
            ),
        ),
        migrations.AddField(
            model_name="uploadrow",
            name="society",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="masterdata.society",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["org", "txn_type", "archived_at"],
                name="inventory_l_broker__b2952f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("org", "unit", "txn_type"),
                name="one_live_listing_per_org_unit_txn",
            ),
        ),
        migrations.AddConstraint(
            model_name="savedcolumnmapping",
            constraint=models.UniqueConstraint(
                fields=("org", "header_signature"), name="uniq_mapping"
            ),
        ),
    ]
