# Generated by Django 5.1.15 on 2026-09-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="owner_phone_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Find a flat by the owner's number",
                max_length=64,
            ),
        ),
    ]


def backfill(apps, schema_editor):
    from common import crypto

    Listing = apps.get_model("inventory", "Listing")
    with schema_editor.connection.cursor() as cur:
        cur.execute("SELECT set_config('app.rls_bypass', 'on', true)")
    for pk, enc in Listing.objects.exclude(owner_phone_enc=None).values_list("pk", "owner_phone_enc"):
        try:
            phone = crypto.decrypt(bytes(enc))
        except Exception:  # noqa: BLE001 - skip unreadable legacy rows
            continue
        if phone:
            Listing.objects.filter(pk=pk).update(owner_phone_hash=crypto.phone_hash(phone))


Migration.operations.append(migrations.RunPython(backfill, migrations.RunPython.noop))
