# Generated by Django 5.1.15 on 2026-09-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_owner_phone_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available_now',
            field=models.BooleanField(default=False),
        ),
    ]
