# Generated by Django 5.2.7 on 2026-01-23 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAuthority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('authority_type', models.CharField(choices=[('CONSTITUTIONAL_BODY', 'Constitutional Body'), ('GOVERNING_COUNCIL', 'Governing Council'), ('EXECUTIVE_AUTHORITY', 'Executive Authority'), ('JUDICIAL_AUTHORITY', 'Judicial Authority'), ('REGULATORY_AUTHORITY', 'Regulatory Authority'), ('ADMIN_AUTHORITY', 'Administrative Authority'), ('EMERGENCY_AUTHORITY', 'Emergency Authority'), ('EXTERNAL_AUTHORITY', 'External Authority')], max_length=50)),
                ('jurisdiction', models.CharField(max_length=255)),
                ('scope', models.JSONField(default=dict, help_text='Spatial, functional, domain scope')),
                ('legal_domain', models.CharField(max_length=100)),
                ('supremacy_rank', models.PositiveIntegerField(help_text='Lower number = higher authority')),
                ('legal_powers', models.JSONField(default=dict, help_text='Structured declaration of legal powers')),
                ('delegation_rights', models.JSONField(default=dict, help_text='Delegable powers and constraints')),
                ('override_rights', models.JSONField(default=dict, help_text='Override capabilities')),
                ('can_create_law', models.BooleanField(default=False)),
                ('can_amend_law', models.BooleanField(default=False)),
                ('can_repeal_law', models.BooleanField(default=False)),
                ('can_interpret_law', models.BooleanField(default=False)),
                ('can_enforce_law', models.BooleanField(default=False)),
                ('governance_binding', models.JSONField(default=dict, help_text='Governance policy bindings')),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_legal_authorities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legal Authority',
                'verbose_name_plural': 'Legal Authorities',
                'ordering': ['supremacy_rank', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalAuthorityRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('SUPERSEDES', 'Supersedes'), ('DELEGATES_TO', 'Delegates To'), ('OVERRIDES', 'Overrides'), ('SUBORDINATE_TO', 'Subordinate To'), ('DERIVES_FROM', 'Derives From')], max_length=50)),
                ('scope', models.JSONField(default=dict, help_text='Contextual scope of this relationship')),
                ('conditions', models.JSONField(default=dict, help_text='Conditional activation rules')),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='legal.legalauthority')),
                ('to_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='legal.legalauthority')),
            ],
            options={
                'verbose_name': 'Legal Authority Relation',
                'verbose_name_plural': 'Legal Authority Relations',
                'unique_together': {('from_authority', 'to_authority', 'relation_type')},
            },
        ),
    ]
