# Generated by Django 5.2.7 on 2026-01-23 16:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalCanonNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('canon_type', models.CharField(choices=[('CONSTITUTION', 'Constitution'), ('PRIMARY_LAW', 'Primary Law'), ('SECONDARY_LAW', 'Secondary Law'), ('PROCEDURAL_LAW', 'Procedural Law'), ('REGULATORY_LAW', 'Regulatory Law'), ('DISCIPLINARY_LAW', 'Disciplinary Law'), ('FINANCIAL_LAW', 'Financial Law'), ('INTERPRETATIVE_LAW', 'Interpretative Law')], max_length=50)),
                ('hierarchy_level', models.PositiveIntegerField()),
                ('jurisdiction', models.CharField(max_length=100)),
                ('scope', models.JSONField(default=dict)),
                ('legal_domain', models.CharField(max_length=100)),
                ('governance_binding', models.JSONField(default=dict)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REPEALED', 'Repealed'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=50)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authority_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canon_nodes', to='legal.legalauthority')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='legal.legalcanonnode')),
            ],
            options={
                'verbose_name': 'Legal Canon Node',
                'verbose_name_plural': 'Legal Canon Nodes',
                'ordering': ['hierarchy_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('doc_type', models.CharField(choices=[('CONSTITUTION', 'Constitution'), ('LAW', 'Law'), ('BYLAW', 'Bylaw'), ('REGULATION', 'Regulation'), ('POLICY', 'Policy'), ('PROCEDURE', 'Procedure'), ('DIRECTIVE', 'Directive'), ('NOTICE', 'Notice'), ('ORDER', 'Order'), ('INTERPRETATION', 'Interpretation')], max_length=50)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('legal_domain', models.CharField(max_length=100)),
                ('hierarchy_level', models.PositiveIntegerField()),
                ('normative_type', models.CharField(max_length=50)),
                ('scope', models.JSONField(default=dict)),
                ('conditions', models.JSONField(default=dict)),
                ('rules', models.JSONField(default=list)),
                ('obligations', models.JSONField(default=list)),
                ('prohibitions', models.JSONField(default=list)),
                ('permissions', models.JSONField(default=list)),
                ('exceptions', models.JSONField(default=list)),
                ('sanctions', models.JSONField(default=list)),
                ('enforcement_bindings', models.JSONField(default=dict)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('governance_binding', models.JSONField(default=dict)),
                ('created_by', models.CharField(max_length=255)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REPEALED', 'Repealed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authority_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='legal.legalauthority')),
                ('canon_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='legal.legalcanonnode')),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
                'ordering': ['hierarchy_level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Bylaw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('legal_domain', models.CharField(max_length=100)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('scope', models.JSONField(default=dict)),
                ('normative_type', models.CharField(max_length=50)),
                ('conditions', models.JSONField(default=dict)),
                ('obligations', models.JSONField(default=list)),
                ('prohibitions', models.JSONField(default=list)),
                ('permissions', models.JSONField(default=list)),
                ('exceptions', models.JSONField(default=list)),
                ('sanctions', models.JSONField(default=list)),
                ('enforcement_hooks', models.JSONField(default=dict)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('governance_binding', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REPEALED', 'Repealed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('authority_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bylaws', to='legal.legalauthority')),
                ('canon_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bylaws', to='legal.legalcanonnode')),
                ('legal_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bylaws', to='legal.legaldocument')),
            ],
            options={
                'verbose_name': 'Bylaw',
                'verbose_name_plural': 'Bylaws',
                'ordering': ['code'],
            },
        ),
    ]
