# Generated by Django 5.1.15 on 2026-09-23 19:51

import common.ids
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.CharField(blank=True, max_length=500)),
                ("brokerage_terms", models.CharField(max_length=200)),
                ("match_count", models.PositiveIntegerField(default=0)),
                ("earliest_slot", models.DateTimeField(blank=True, null=True)),
                (
                    "teaser_society_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("response_s", models.PositiveIntegerField()),
                ("promoted", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="sent",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplyCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("h3_index", models.CharField(max_length=16)),
                ("resolution", models.PositiveSmallIntegerField()),
                ("txn_type", models.CharField(max_length=12)),
                ("bhk_bucket", models.CharField(max_length=4)),
                ("units_available", models.PositiveIntegerField()),
                ("price_p25", models.PositiveBigIntegerField(null=True)),
                ("price_p50", models.PositiveBigIntegerField(null=True)),
                ("price_p75", models.PositiveBigIntegerField(null=True)),
                ("brokers_serving", models.PositiveIntegerField(default=0)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("refreshed_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("txn_type", models.CharField(max_length=12)),
                (
                    "property_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("bhk_min", models.DecimalField(decimal_places=1, max_digits=3)),
                ("bhk_max", models.DecimalField(decimal_places=1, max_digits=3)),
                ("budget_min", models.PositiveBigIntegerField(blank=True, null=True)),
                ("budget_max", models.PositiveBigIntegerField()),
                (
                    "center",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("radius_m", models.PositiveIntegerField(default=3000)),
                ("area_label", models.CharField(blank=True, max_length=120)),
                ("must_haves", models.JSONField(blank=True, default=dict)),
                ("house_rule_needs", models.JSONField(blank=True, default=dict)),
                (
                    "max_station_distance_m",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("move_in_by", models.DateField(blank=True, null=True)),
                ("urgency", models.CharField(default="normal", max_length=8)),
                ("occupants", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("summary_text", models.CharField(max_length=300)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("n_recipients", models.PositiveIntegerField(default=0)),
                (
                    "customer_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnquiryDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel", models.CharField(max_length=10)),
                ("match_count", models.PositiveIntegerField(default=0)),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="marketplace.enquiry",
                    ),
                ),
            ],
        ),
    ]
