# Generated by Django 5.1.15 on 2026-09-23 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0001_initial"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="enquirydelivery",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="orgs.brokerorg",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="enquiry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals",
                to="marketplace.enquiry",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals",
                to="orgs.brokerorg",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="sent_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="supplycell",
            index=models.Index(
                fields=["resolution", "txn_type"], name="marketplace_resolut_975be1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplycell",
            constraint=models.UniqueConstraint(
                fields=("h3_index", "txn_type", "bhk_bucket"), name="uniq_cell"
            ),
        ),
        migrations.AddIndex(
            model_name="enquiry",
            index=models.Index(
                fields=["state", "created_at"], name="marketplace_state_5e505b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="enquirydelivery",
            constraint=models.UniqueConstraint(
                fields=("enquiry", "org"), name="one_delivery_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.UniqueConstraint(
                fields=("enquiry", "org"), name="one_proposal_per_org"
            ),
        ),
    ]
