DEFAULT_MAINTENANCE_HEADS = [

    # =====================================================
    # CORE RECURRING MAINTENANCE HEADS
    # =====================================================

    {
        "code": "SERVICE_CHARGES",
        "name": "Service Charges",
        "description": "Administrative and common operational expenses shared equally across all flats.",
        "category": "CORE",
        "default_basis": "EQUAL",
        "suggested_rate": 1500,
        "enabled_by_default": True,
        "editable_basis": True,
        "editable_rate": True,
        "recommended": True,
        "applicability": "ALL_FLATS",
    },

    {
        "code": "REPAIRS_MAINTENANCE",
        "name": "Repairs & Maintenance",
        "description": "Routine repairs and building maintenance expenses.",
        "category": "CORE",
        "default_basis": "AREA",
        "suggested_rate": 2,
        "enabled_by_default": True,
        "editable_basis": True,
        "editable_rate": True,
        "recommended": True,
        "applicability": "ALL_FLATS",
    },

    {
        "code": "SINKING_FUND",
        "name": "Sinking Fund",
        "description": "Long-term reserve fund for structural and major future repairs.",
        "category": "CORE",
        "default_basis": "AREA",
        "suggested_rate": 1,
        "enabled_by_default": True,
        "editable_basis": True,
        "editable_rate": True,
        "recommended": True,
        "applicability": "ALL_FLATS",
    },

    {
        "code": "COMMON_ELECTRICITY",
        "name": "Common Electricity",
        "description": "Electricity charges for common areas, pumps, staircase lighting, and shared infrastructure.",
        "category": "CORE",
        "default_basis": "AREA",
        "suggested_rate": 1.5,
        "enabled_by_default": True,
        "editable_basis": True,
        "editable_rate": True,
        "recommended": True,
        "applicability": "ALL_FLATS",
    },

    {
        "code": "WATER_CHARGES",
        "name": "Water Charges",
        "description": "Water supply and common water infrastructure expenses.",
        "category": "CORE",
        "default_basis": "EQUAL",
        "suggested_rate": 800,
        "enabled_by_default": True,
        "editable_basis": True,
        "editable_rate": True,
        "recommended": True,
        "applicability": "ALL_FLATS",
    },

    {
        "code": "LIFT_MAINTENANCE",
        "name": "Lift Maintenance",
        "description": "Lift AMC, repairs, servicing, and operational expenses.",
        "category": "CORE",
        "default_basis": "AREA",
        "suggested_rate": 1,
        "enabled_by_default": True,
        "editable_basis": True,
        "editable_rate": True,
        "recommended": True,
        "applicability": "ALL_FLATS",
    },

    {
        "code": "SECURITY_CHARGES",
        "name": "Security Charges",
        "description": "Security staff, agencies, and surveillance operational expenses.",
        "category": "CORE",
        "default_basis": "EQUAL",
        "suggested_rate": 1200,
        "enabled_by_default": True,
        "editable_basis": True,
        "editable_rate": True,
        "recommended": True,
        "applicability": "ALL_FLATS",
    },

    {
        "code": "HOUSEKEEPING",
        "name": "Housekeeping Charges",
        "description": "Cleaning and housekeeping expenses for common areas.",
        "category": "CORE",
        "default_basis": "EQUAL",
        "suggested_rate": 700,
        "enabled_by_default": True,
        "editable_basis": True,
        "editable_rate": True,
        "recommended": True,
        "applicability": "ALL_FLATS",
    },

    {
        "code": "BUILDING_INSURANCE",
        "name": "Building Insurance",
        "description": "Building insurance premium recovery contribution.",
        "category": "CORE",
        "default_basis": "AREA",
        "suggested_rate": 0.5,
        "enabled_by_default": True,
        "editable_basis": True,
        "editable_rate": True,
        "recommended": True,
        "applicability": "ALL_FLATS",
    },

    # =====================================================
    # OPTIONAL / CONDITIONAL HEADS
    # =====================================================

    {
        "code": "PARKING_CHARGES",
        "name": "Parking Charges",
        "description": "Charges applicable for allotted parking slots.",
        "category": "OPTIONAL",
        "default_basis": "PER_SLOT",
        "suggested_rate": 500,
        "enabled_by_default": False,
        "editable_basis": True,
        "editable_rate": True,
        "recommended": True,
        "applicability": "PARKING_ONLY",
    },

    {
        "code": "NON_OCCUPANCY",
        "name": "Non Occupancy Charges",
        "description": "Charges applicable for rented or licensed flats.",
        "category": "OPTIONAL",
        "default_basis": "PERCENT_MAINT",
        "suggested_rate": 10,
        "enabled_by_default": False,
        "editable_basis": False,
        "editable_rate": True,
        "recommended": True,
        "applicability": "RENTED_ONLY",
    },

    {
        "code": "CCTV_MAINTENANCE",
        "name": "CCTV Maintenance",
        "description": "Maintenance expenses for CCTV and surveillance systems.",
        "category": "OPTIONAL",
        "default_basis": "EQUAL",
        "suggested_rate": 300,
        "enabled_by_default": False,
        "editable_basis": True,
        "editable_rate": True,
        "recommended": False,
        "applicability": "ALL_FLATS",
    },

    {
        "code": "GENERATOR_CHARGES",
        "name": "Generator Charges",
        "description": "Diesel generator maintenance and operational expenses.",
        "category": "OPTIONAL",
        "default_basis": "AREA",
        "suggested_rate": 0.75,
        "enabled_by_default": False,
        "editable_basis": True,
        "editable_rate": True,
        "recommended": False,
        "applicability": "ALL_FLATS",
    },

    {
        "code": "WATER_TANKER",
        "name": "Water Tanker Recovery",
        "description": "Water tanker procurement and recovery charges.",
        "category": "OPTIONAL",
        "default_basis": "EQUAL",
        "suggested_rate": 500,
        "enabled_by_default": False,
        "editable_basis": True,
        "editable_rate": True,
        "recommended": False,
        "applicability": "ALL_FLATS",
    },

]