# Generated by Django 5.1.15 on 2026-09-23 19:51

import common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0003_initial"),
        ("inventory", "0002_initial"),
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requirement_version", models.PositiveIntegerField()),
                ("include_unconfirmed", models.BooleanField(default=True)),
                ("n_considered", models.PositiveIntegerField(default=0)),
                ("n_matched", models.PositiveIntegerField(default=0)),
                (
                    "org",
                    models.ForeignKey(
                        db_column="broker_org_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="orgs.brokerorg",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_runs",
                        to="crm.requirement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.PositiveSmallIntegerField()),
                ("excluded", models.BooleanField(default=False)),
                ("explanation", models.JSONField(default=list)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="inventory.listing",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        db_column="broker_org_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="orgs.brokerorg",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="matching.matchrun",
                    ),
                ),
            ],
            options={
                "ordering": ["excluded", "-score"],
            },
        ),
    ]
