# Generated by Django 5.2.7 on 2026-02-18 20:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('society', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BylawChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('sequence_order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='BylawDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_code', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('IDENTITY', 'Identity'), ('MEMBERSHIP', 'Membership'), ('SHARE_CAPITAL', 'Share Capital'), ('COMMITTEE', 'Committee Structure'), ('FINANCE', 'Finance'), ('USAGE', 'Usage'), ('TENANCY', 'Tenancy'), ('TRANSFER', 'Transfer'), ('COMPLIANCE', 'Compliance'), ('DISCIPLINE', 'Discipline')], max_length=40)),
                ('question', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('legal_reference', models.TextField(blank=True)),
                ('allowed_values', models.JSONField(blank=True, default=dict)),
                ('default_value', models.JSONField(blank=True, default=dict)),
                ('risk_rules', models.JSONField(blank=True, default=dict)),
                ('registrar_notes', models.TextField(blank=True)),
                ('clause_template_code', models.CharField(blank=True, max_length=120)),
                ('sequence_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BylawVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegalObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('mandatory', models.BooleanField(default=True)),
                ('reference_law', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LegalStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sequence_order', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('expected_duration_days', models.PositiveIntegerField(default=30)),
                ('amber_after_days', models.PositiveIntegerField(default=45)),
                ('red_after_days', models.PositiveIntegerField(default=60)),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BylawClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clause_number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('legal_text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('machine_tags', models.JSONField(blank=True, default=dict)),
                ('sequence_order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='statutory.bylawchapter')),
            ],
            options={
                'ordering': ['sequence_order'],
                'unique_together': {('chapter', 'clause_number')},
            },
        ),
        migrations.CreateModel(
            name='BylawDecisionHook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_code', models.CharField(max_length=100)),
                ('enforcement_level', models.CharField(choices=[('INFO', 'Informational'), ('ADVISORY', 'Advisory'), ('SOFT_BLOCK', 'Soft Block'), ('HARD_BLOCK', 'Hard Block')], default='ADVISORY', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_hooks', to='statutory.bylawclause')),
            ],
        ),
        migrations.CreateModel(
            name='BylawDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.CharField(default='MH-2014', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('approved_by_committee', models.BooleanField(default=False)),
                ('registrar_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='society.case')),
            ],
        ),
        migrations.CreateModel(
            name='BylawDraftDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_key', models.CharField(max_length=100)),
                ('decision_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statutory.bylawdraft')),
            ],
        ),
        migrations.AddField(
            model_name='bylawchapter',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='statutory.bylawversion'),
        ),
        migrations.CreateModel(
            name='LegalChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('mandatory', models.BooleanField(default=True)),
                ('legal_obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statutory.legalobligation')),
            ],
        ),
        migrations.CreateModel(
            name='LegalArtifactTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('FORM', 'Form'), ('LETTER', 'Letter'), ('RESOLUTION', 'Resolution'), ('MINUTES', 'Minutes')], max_length=32)),
                ('artifact_code', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('template_body', models.TextField(help_text='Template body with placeholders like {{ society_name }}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_templates', to='statutory.legalobligation')),
            ],
            options={
                'ordering': ['artifact_code'],
            },
        ),
        migrations.AddField(
            model_name='legalobligation',
            name='legal_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statutory.legalstage'),
        ),
        migrations.CreateModel(
            name='SocietyLegalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERRIDDEN', 'Overridden')], max_length=20)),
                ('started_on', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('legal_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statutory.legalstage')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.society')),
            ],
        ),
        migrations.CreateModel(
            name='SocietyObligationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('overridden_on', models.DateTimeField(blank=True, null=True)),
                ('legal_obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statutory.legalobligation')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.society')),
            ],
        ),
        migrations.AddField(
            model_name='legalstage',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statutory.state'),
        ),
        migrations.CreateModel(
            name='StatutoryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('STEP_COMPLETED', 'Step Completed'), ('STEP_STARTED', 'Step Started'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('SYSTEM', 'System Action')], max_length=50)),
                ('description', models.TextField()),
                ('source', models.CharField(default='API', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statutory.legalstage')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='society.society')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BylawSubClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_clause_number', models.CharField(max_length=10)),
                ('legal_text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('sequence_order', models.PositiveIntegerField()),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_clauses', to='statutory.bylawclause')),
            ],
            options={
                'ordering': ['sequence_order'],
                'unique_together': {('clause', 'sub_clause_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bylawchapter',
            unique_together={('version', 'chapter_number')},
        ),
        migrations.CreateModel(
            name='DecisionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='statutory.bylawdecision')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_sessions', to='statutory.bylawdraft')),
            ],
            options={
                'unique_together': {('draft', 'decision')},
            },
        ),
        migrations.CreateModel(
            name='ShareOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('acquired_on', models.DateField(default=django.utils.timezone.now)),
                ('relinquished_on', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_ownerships', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_ownerships', to='society.society')),
            ],
            options={
                'ordering': ['-acquired_on'],
                'indexes': [models.Index(fields=['society', 'is_active'], name='statutory_s_society_4f834d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocietyBylawDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforcement_level', models.CharField(choices=[('ADVISORY', 'Advisory'), ('SOFT_BLOCK', 'Soft Block'), ('HARD_BLOCK', 'Hard Block'), ('CONDITIONAL', 'Conditional')], default='ADVISORY', max_length=20)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_values', to='statutory.bylawdecision')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bylaw_decisions', to='society.society')),
            ],
            options={
                'unique_together': {('society', 'decision')},
            },
        ),
        migrations.CreateModel(
            name='SocietyLegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='legal_documents/')),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('UPLOADED', 'Uploaded'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], default='GENERATED', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_documents', to='society.society')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to='statutory.legalartifacttemplate')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('society', 'template')},
            },
        ),
    ]
