# Generated by Django 5.2.7 on 2025-12-27 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('society', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('mandatory', models.BooleanField(default=True)),
                ('reference_law', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LegalStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sequence_order', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LegalChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('mandatory', models.BooleanField(default=True)),
                ('legal_obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statutory.legalobligation')),
            ],
        ),
        migrations.CreateModel(
            name='LegalArtifactTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('FORM', 'Form'), ('RESOLUTION', 'Resolution'), ('NOTICE', 'Notice'), ('REGISTER', 'Register')], max_length=20)),
                ('template_body', models.TextField()),
                ('legal_obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statutory.legalobligation')),
            ],
        ),
        migrations.AddField(
            model_name='legalobligation',
            name='legal_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statutory.legalstage'),
        ),
        migrations.CreateModel(
            name='SocietyLegalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERRIDDEN', 'Overridden')], max_length=20)),
                ('started_on', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('legal_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statutory.legalstage')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.society')),
            ],
        ),
        migrations.CreateModel(
            name='SocietyObligationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('overridden_on', models.DateTimeField(blank=True, null=True)),
                ('legal_obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statutory.legalobligation')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.society')),
            ],
        ),
        migrations.AddField(
            model_name='legalstage',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statutory.state'),
        ),
    ]
