# Generated by Django 5.2.7 on 2026-02-24 16:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bylaws', '0002_alter_bylawchapter_table_alter_bylawclause_table_and_more'),
        ('society', '0001_initial'),
        ('statutory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bylawchapter',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bylawchapter',
            name='version',
        ),
        migrations.RemoveField(
            model_name='bylawclause',
            name='chapter',
        ),
        migrations.AlterUniqueTogether(
            name='bylawclause',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bylawsubclause',
            name='clause',
        ),
        migrations.RemoveField(
            model_name='bylawdecisionhook',
            name='clause',
        ),
        migrations.AlterField(
            model_name='societybylawdecision',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_values', to='bylaws.bylawdecision'),
        ),
        migrations.RemoveField(
            model_name='decisionsession',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='bylawdraft',
            name='case',
        ),
        migrations.RemoveField(
            model_name='decisionsession',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='bylawdraftdecision',
            name='draft',
        ),
        migrations.AlterUniqueTogether(
            name='bylawsubclause',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='decisionsession',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='BylawVersion',
        ),
        migrations.DeleteModel(
            name='BylawChapter',
        ),
        migrations.DeleteModel(
            name='BylawSubClause',
        ),
        migrations.DeleteModel(
            name='BylawClause',
        ),
        migrations.DeleteModel(
            name='BylawDecisionHook',
        ),
        migrations.DeleteModel(
            name='BylawDecision',
        ),
        migrations.DeleteModel(
            name='DecisionSession',
        ),
        migrations.DeleteModel(
            name='BylawDraft',
        ),
        migrations.DeleteModel(
            name='BylawDraftDecision',
        ),
    ]
