# Generated by Django 5.2.7 on 2026-02-25 03:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
        ('statutory', '0002_alter_bylawchapter_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('snapshot_hash', models.CharField(help_text='Integrity hash of prereg snapshot at submission time', max_length=128)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACKNOWLEDGED', 'Acknowledged'), ('QUERIED', 'Queried by Registrar'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('registrar_reference', models.CharField(blank=True, help_text='Registrar file/reference number', max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrar_submissions', to='society.society')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['society', 'status'], name='statutory_r_society_4b97bf_idx')],
            },
        ),
    ]
