# Generated by Django 5.2.7 on 2025-12-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statutory', '0002_seed_maharashtra_legal_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalstage',
            name='amber_after_days',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AddField(
            model_name='legalstage',
            name='expected_duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='legalstage',
            name='red_after_days',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
