# Generated by Django 5.2.7 on 2025-12-28 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
        ('statutory', '0003_legalstage_amber_after_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('STEP_COMPLETED', 'Step Completed'), ('STEP_STARTED', 'Step Started'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('SYSTEM', 'System Action')], max_length=50)),
                ('description', models.TextField()),
                ('source', models.CharField(default='API', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statutory.legalstage')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='society.society')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
