# Generated by Django 5.2.7 on 2026-03-12 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statutory', '0004_societyregistrationapproval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legalobligation',
            old_name='mandatory',
            new_name='is_mandatory',
        ),
        migrations.AddField(
            model_name='legalobligation',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalobligation',
            name='sequence_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='legalobligation',
            name='legal_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='statutory.legalstage'),
        ),
    ]
