# Generated by Django 5.2.7 on 2025-12-28 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
        ('statutory', '0004_statutoryauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyLegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='legal_documents/')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='UPLOADED', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_documents', to='society.society')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to='statutory.legalartifacttemplate')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('society', 'template')},
            },
        ),
    ]
