# Generated by Django 5.2.7 on 2026-01-03 06:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0004_delete_shareownership'),
        ('statutory', '0005_societylegaldocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='societylegaldocument',
            name='status',
            field=models.CharField(choices=[('GENERATED', 'Generated'), ('UPLOADED', 'Uploaded'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], default='GENERATED', max_length=20),
        ),
        migrations.CreateModel(
            name='ShareOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('acquired_on', models.DateField(default=django.utils.timezone.now)),
                ('relinquished_on', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_ownerships', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_ownerships', to='society.society')),
            ],
            options={
                'ordering': ['-acquired_on'],
                'indexes': [models.Index(fields=['society', 'is_active'], name='statutory_s_society_4f834d_idx')],
            },
        ),
    ]
