# Generated by Django 5.2.7 on 2026-04-07 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0032_committee_unique_active_committee_per_society'),
        ('statutory', '0006_create_society_consent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyBylaws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('generated_document_path', models.CharField(help_text='Path to generated (soft copy) bylaws', max_length=500)),
                ('signed_document_path', models.CharField(blank=True, help_text='Path to signed (uploaded) bylaws', max_length=500, null=True)),
                ('governance_hooks_json', models.JSONField(help_text='Snapshot of governance decisions at time of generation')),
                ('status', models.CharField(
                    choices=[
                        ('DRAFT', 'Draft'),
                        ('GENERATED', 'Generated'),
                        ('SIGNED', 'Signed'),
                        ('ACTIVE', 'Active'),
                        ('SUPERSEDED', 'Superseded')
                    ],
                    default='DRAFT',
                    max_length=20
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='approved_bylaws',
                    to=settings.AUTH_USER_MODEL
                )),
                ('society', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='society_bylaws',
                    to='society.society'
                )),
            ],
            options={
                'ordering': ['-version_number'],
                'indexes': [
                    models.Index(fields=['society', 'status'], name='statutory_s_society_ca06e8_idx')
                ],
            },
        ),
    ]