# Generated by Django 5.2.7 on 2026-04-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statutory', '0007_alter_legalobligation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalobligation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='legalobligation',
            name='reference_law',
            field=models.CharField(max_length=255),
        ),
    ]
