# Generated by Django 5.2.7 on 2026-02-03 16:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statutory', '0007_seed_stage0_maharashtra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalartifacttemplate',
            options={'ordering': ['artifact_code']},
        ),
        migrations.AddField(
            model_name='legalartifacttemplate',
            name='artifact_code',
            field=models.CharField(
                max_length=64,
                null=True,
                blank=True,
                db_index=True,   # keep lookup fast
            ),
        ),

        migrations.AddField(
            model_name='legalartifacttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalartifacttemplate',
            name='artifact_type',
            field=models.CharField(choices=[('FORM', 'Form'), ('LETTER', 'Letter'), ('RESOLUTION', 'Resolution'), ('MINUTES', 'Minutes')], max_length=32),
        ),
        migrations.AlterField(
            model_name='legalartifacttemplate',
            name='legal_obligation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_templates', to='statutory.legalobligation'),
        ),
        migrations.AlterField(
            model_name='legalartifacttemplate',
            name='template_body',
            field=models.TextField(help_text='Template body with placeholders like {{ society_name }}'),
        ),
    ]
