# Generated by Django 5.2.7 on 2026-02-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statutory', '0008_alter_legalartifacttemplate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BylawDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_code', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('IDENTITY', 'Identity'), ('MEMBERSHIP', 'Membership'), ('SHARE_CAPITAL', 'Share Capital'), ('COMMITTEE', 'Committee Structure'), ('FINANCE', 'Finance'), ('USAGE', 'Usage'), ('TENANCY', 'Tenancy'), ('TRANSFER', 'Transfer'), ('COMPLIANCE', 'Compliance'), ('DISCIPLINE', 'Discipline')], max_length=40)),
                ('question', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('legal_reference', models.TextField(blank=True)),
                ('allowed_values', models.JSONField(blank=True, default=dict)),
                ('default_value', models.JSONField(blank=True, default=dict)),
                ('risk_rules', models.JSONField(blank=True, default=dict)),
                ('registrar_notes', models.TextField(blank=True)),
                ('clause_template_code', models.CharField(blank=True, max_length=120)),
                ('sequence_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
