# Generated by Django 5.2.7 on 2026-02-10 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0042_society_state_code'),
        ('statutory', '0009_bylawdecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyBylawDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_values', to='statutory.bylawdecision')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bylaw_decisions', to='society.society')),
            ],
            options={
                'unique_together': {('society', 'decision')},
            },
        ),
    ]
