# Generated by Django 5.2.7 on 2026-02-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statutory', '0010_societybylawdecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='societybylawdecision',
            name='enforcement_level',
            field=models.CharField(choices=[('ADVISORY', 'Advisory'), ('SOFT_BLOCK', 'Soft Block'), ('HARD_BLOCK', 'Hard Block'), ('CONDITIONAL', 'Conditional')], default='ADVISORY', max_length=20),
        ),
    ]
