# Generated by Django 5.2.7 on 2026-02-10 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statutory', '0011_societybylawdecision_enforcement_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='BylawChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('sequence_order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='BylawVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BylawClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clause_number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('legal_text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('machine_tags', models.JSONField(blank=True, default=dict)),
                ('sequence_order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='statutory.bylawchapter')),
            ],
            options={
                'ordering': ['sequence_order'],
                'unique_together': {('chapter', 'clause_number')},
            },
        ),
        migrations.CreateModel(
            name='BylawDecisionHook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_code', models.CharField(max_length=100)),
                ('enforcement_level', models.CharField(choices=[('INFO', 'Informational'), ('ADVISORY', 'Advisory'), ('SOFT_BLOCK', 'Soft Block'), ('HARD_BLOCK', 'Hard Block')], default='ADVISORY', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_hooks', to='statutory.bylawclause')),
            ],
        ),
        migrations.AddField(
            model_name='bylawchapter',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='statutory.bylawversion'),
        ),
        migrations.CreateModel(
            name='BylawSubClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_clause_number', models.CharField(max_length=10)),
                ('legal_text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('sequence_order', models.PositiveIntegerField()),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_clauses', to='statutory.bylawclause')),
            ],
            options={
                'ordering': ['sequence_order'],
                'unique_together': {('clause', 'sub_clause_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bylawchapter',
            unique_together={('version', 'chapter_number')},
        ),
    ]
