# Generated by Django 5.2.7 on 2026-02-17 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0045_casestage'),
        ('statutory', '0012_bylawchapter_bylawversion_bylawclause_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BylawDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.CharField(default='MH-2014', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('approved_by_committee', models.BooleanField(default=False)),
                ('registrar_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='society.case')),
            ],
        ),
    ]
