# Generated by Django 5.1.15 on 2026-09-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
