# Generated by Django 5.1.15 on 2026-09-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("seq", models.BigAutoField(primary_key=True, serialize=False)),
                ("at", models.DateTimeField()),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                ("actor_label", models.CharField(blank=True, max_length=60)),
                ("action", models.CharField(db_index=True, max_length=80)),
                ("target_type", models.CharField(max_length=60)),
                ("target_id", models.CharField(max_length=64)),
                ("data", models.JSONField(default=dict)),
                ("prev_hash", models.CharField(max_length=64)),
                ("hash", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_audit_target__59bbff_idx",
                    )
                ],
            },
        ),
    ]
