# society/constants.py

LEDGER_ALLOCATION_ORDER = [
    "MAINTENANCE",
    "PARKING",
    "NON_OCCUPANCY_CHARGE",
    "SPECIAL_CHARGE",
    "PENALTY",
]
class TransactionType:
    MAINTENANCE_RECEIPT = "MAINTENANCE_RECEIPT"
    PARKING_RECEIPT = "PARKING_RECEIPT"
    INTEREST_RECEIPT = "INTEREST_RECEIPT"

    SALARY_PAYMENT = "SALARY_PAYMENT"
    ELECTRICITY_PAYMENT = "ELECTRICITY_PAYMENT"
    REPAIR_PAYMENT = "REPAIR_PAYMENT"

    ADVANCE_ADJUSTMENT = "ADVANCE_ADJUSTMENT"
from enum import Enum

class TransactionType(str, Enum):
    MAINTENANCE_RECEIPT = "MAINTENANCE_RECEIPT"
    MAINTENANCE_BILL = "MAINTENANCE_BILL"

    ELECTRICITY_BILL_PAYMENT = "ELECTRICITY_BILL_PAYMENT"
    SALARY_PAYMENT = "SALARY_PAYMENT"

    BANK_DEPOSIT = "BANK_DEPOSIT"
    BANK_WITHDRAWAL = "BANK_WITHDRAWAL"

    FD_CREATION = "FD_CREATION"
    FD_INTEREST_RECEIVED = "FD_INTEREST_RECEIVED"

    PENALTY_CHARGED = "PENALTY_CHARGED"
