# Generated by Django 5.2.7 on 2026-02-18 20:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Mandatory for all flats')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=128)),
                ('actor_id', models.CharField(blank=True, max_length=64, null=True)),
                ('domain', models.CharField(max_length=64)),
                ('object_type', models.CharField(max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('event_hash', models.CharField(db_index=True, editable=False, max_length=64)),
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChargeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_percentage', models.BooleanField(default=False, help_text='If true, charge is a percentage-based calculation')),
                ('max_percentage_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed percentage (e.g. 10.00 for NOC)', max_digits=5, null=True)),
                ('applies_on', models.CharField(choices=[('SERVICE_CHARGES', 'Service Charges'), ('MAINTENANCE', 'Maintenance'), ('NONE', 'Not Applicable')], default='NONE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('RESERVE', 'Reserve')], max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_system', models.BooleanField(default=False, help_text='System-generated account (do not delete)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(help_text='Flat number as per society records (e.g. A-101, 1203)', max_length=20)),
                ('wing', models.CharField(blank=True, help_text='Wing / building identifier (if applicable)', max_length=20, null=True)),
                ('floor', models.IntegerField(blank=True, help_text='Floor number', null=True)),
                ('carpet_area_sqft', models.DecimalField(blank=True, decimal_places=2, help_text='Carpet area in square feet', max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this flat is active (not merged / demolished)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['flat_number'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField(help_text='First day of the billing month')),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['-billing_month'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=20)),
                ('parking_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('VISITOR', 'Visitor')], max_length=20)),
                ('allocation_type', models.CharField(choices=[('FLAT', 'Flat Allotted'), ('MEMBER', 'Member Allotted'), ('COMMON', 'Common Use')], default='COMMON', max_length=20)),
                ('is_chargeable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmenityChargeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('FREE', 'Free'), ('FIXED', 'Fixed Monthly'), ('PER_USE', 'Per Use'), ('PER_FLAT', 'Per Flat')], default='FREE', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly or per-use amount', max_digits=10, null=True)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('amenity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charge_rule', to='society.amenity')),
            ],
            options={
                'ordering': ['effective_from'],
            },
        ),
        migrations.CreateModel(
            name='FlatOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy_type', models.CharField(choices=[('SELF', 'Self Occupied'), ('RENTED', 'Rented / Leave & License'), ('FAMILY', 'Occupied by Family'), ('VACANT', 'Vacant / Locked'), ('CORPORATE', 'Corporate Occupancy')], default='SELF', max_length=20)),
                ('declared_on', models.DateField(auto_now=True)),
                ('flat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy', to='society.flat')),
            ],
        ),
        migrations.CreateModel(
            name='FlatOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_on', models.DateField()),
                ('relinquished_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='society.flat')),
            ],
            options={
                'ordering': ['-acquired_on'],
            },
        ),
        migrations.CreateModel(
            name='FlatOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_entity_name', models.CharField(blank=True, help_text='Company / Trust / Entity name (if applicable)', max_length=255, null=True)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, help_text='Ownership percentage (e.g. 50.00)', max_digits=5)),
                ('user', models.ForeignKey(blank=True, help_text='Linked user account (if individual)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='society.flatownership')),
            ],
        ),
        migrations.CreateModel(
            name='FlatRecoveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('NONE', 'No Recovery'), ('REMINDER', 'Reminder Issued'), ('DEMAND', 'Demand Notice'), ('FINAL', 'Final Notice'), ('REGISTRAR', 'Filed with Registrar'), ('LEGAL', 'Legal Proceedings'), ('CLOSED', 'Recovered / Closed')], default='NONE', max_length=20)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_action_on', models.DateField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('flat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_status', to='society.flat')),
            ],
        ),
        migrations.CreateModel(
            name='IntelligenceMemoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('node_id', models.CharField(max_length=128)),
                ('workflow_id', models.CharField(blank=True, max_length=128, null=True)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['node_id'], name='society_int_node_id_7bd56b_idx'), models.Index(fields=['workflow_id'], name='society_int_workflo_ee7942_idx'), models.Index(fields=['event_type'], name='society_int_event_t_daa663_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_paid_on', models.DateField(blank=True, null=True)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_billed_on', models.DateField(blank=True, null=True)),
                ('is_defaulter', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('CLEAR', 'No Dues'), ('OVERDUE', 'Overdue'), ('NOTICE_SENT', 'Notice Issued'), ('RESOLUTION_PASSED', 'Resolution Passed'), ('LEGAL', 'Legal Recovery')], default='CLEAR', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_account', to='society.flat')),
            ],
        ),
        migrations.CreateModel(
            name='FlatMaintenanceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('non_occupancy_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.flat')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_bills', to='society.maintenancebill')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_on', models.DateField()),
                ('released_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_allocations', to='society.flat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_allocations', to=settings.AUTH_USER_MODEL)),
                ('parking_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='society.parkingslot')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('prereg', 'Pre-Registration'), ('handover', 'Builder Handover'), ('legal', 'Legal')], default='prereg', max_length=20)),
                ('status', models.CharField(default='initiated', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.person')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('NONE', 'No Recovery'), ('REMINDER', 'Reminder Issued'), ('DEMAND', 'Demand Notice'), ('FINAL', 'Final Notice'), ('REGISTRAR', 'Filed with Registrar'), ('LEGAL', 'Legal Proceedings'), ('CLOSED', 'Recovered / Closed')], max_length=20)),
                ('action_date', models.DateField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, help_text='Notice number / Registrar file no / etc', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_actions', to='society.flat')),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('registration_number', models.CharField(db_index=True, help_text='Official society registration number issued by Registrar', max_length=50, unique=True)),
                ('registration_date', models.DateField(blank=True, help_text='Date of registration with Registrar', null=True)),
                ('registrar_office', models.CharField(blank=True, help_text='Registrar office / ward / zone', max_length=255)),
                ('state_code', models.CharField(default='MH', help_text='Legal jurisdiction state code (MH, KA, DL, etc.)', max_length=10)),
                ('legal_status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROCESS', 'In Process'), ('LEGALLY_COMPLETE', 'Legally Complete')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('registration_number',), name='unique_society_registration_number')],
            },
        ),
        migrations.CreateModel(
            name='PendingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('MAINTENANCE_RECEIPT', 'MAINTENANCE_RECEIPT'), ('MAINTENANCE_BILL', 'MAINTENANCE_BILL'), ('ELECTRICITY_BILL_PAYMENT', 'ELECTRICITY_BILL_PAYMENT'), ('SALARY_PAYMENT', 'SALARY_PAYMENT'), ('BANK_DEPOSIT', 'BANK_DEPOSIT'), ('BANK_WITHDRAWAL', 'BANK_WITHDRAWAL'), ('FD_CREATION', 'FD_CREATION'), ('FD_INTEREST_RECEIVED', 'FD_INTEREST_RECEIVED'), ('PENALTY_CHARGED', 'PENALTY_CHARGED')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField()),
                ('entry_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_transactions', to='society.society')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('ONLINE', 'Online Gateway')], max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Cheque no / UTR / Txn ID', max_length=100, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('CLEARED', 'Cleared'), ('BOUNCED', 'Bounced'), ('REVERSED', 'Reversed')], default='RECEIVED', max_length=20)),
                ('received_on', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, help_text='Null if advance or miscellaneous payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='society.maintenancebill')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='society.flat')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='society.society')),
            ],
            options={
                'ordering': ['-received_on', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_slots', to='society.society'),
        ),
        migrations.CreateModel(
            name='NoticeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(choices=[('REMINDER', 'Reminder'), ('DEMAND', 'Demand'), ('FINAL', 'Final Notice'), ('LEGAL', 'Legal Notice')], max_length=20)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_period', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('generated_on', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='society.flat')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='society.society')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='maintenancebill',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_bills', to='society.society'),
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField()),
                ('entry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_type', models.CharField(blank=True, help_text='BILL / PAYMENT / ADJUSTMENT / OPENING', max_length=50)),
                ('source_ref', models.CharField(blank=True, help_text='External reference ID', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='society.chartofaccount')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_entries', to='society.chartofaccount')),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='society.flat')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='society.society')),
            ],
            options={
                'ordering': ['entry_date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='flat',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='society.society'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_of_accounts', to='society.society'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='society.society'),
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_periods', to='society.society')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SocietyChargeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percentage or flat amount depending on charge type', max_digits=8)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='society.chargetype')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_rules', to='society.society')),
            ],
        ),
        migrations.CreateModel(
            name='SocietyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('INTEREST', 'Interest'), ('NON_OCCUPANCY', 'Non Occupancy Charge'), ('LATE_FEE', 'Late Fee')], max_length=30)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percentage rate (e.g. 10.00 for 10%)', max_digits=6)),
                ('cap_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum cap if applicable', max_digits=6, null=True)),
                ('applies_after_days', models.PositiveIntegerField(default=0, help_text='Grace period before rule applies')),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.society')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('MAINTENANCE_RECEIPT', 'MAINTENANCE_RECEIPT'), ('MAINTENANCE_BILL', 'MAINTENANCE_BILL'), ('ELECTRICITY_BILL_PAYMENT', 'ELECTRICITY_BILL_PAYMENT'), ('SALARY_PAYMENT', 'SALARY_PAYMENT'), ('BANK_DEPOSIT', 'BANK_DEPOSIT'), ('BANK_WITHDRAWAL', 'BANK_WITHDRAWAL'), ('FD_CREATION', 'FD_CREATION'), ('FD_INTEREST_RECEIVED', 'FD_INTEREST_RECEIVED'), ('PENALTY_CHARGED', 'PENALTY_CHARGED')], max_length=50)),
                ('debit_account_code', models.CharField(max_length=20)),
                ('credit_account_code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_rules', to='society.society')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_code', models.CharField(choices=[('member_list', 'Member List'), ('share_structure', 'Share Structure'), ('entrance_fees', 'Entrance Fees'), ('promoter_affidavit', 'Promoter Affidavit'), ('bank_account', 'Bank Account'), ('building_docs', 'Building Documents'), ('oc_cc', 'OC / CC'), ('land_docs', 'Land Documents'), ('builder_noc', 'Builder NOC'), ('society_resolution', 'Society Resolution'), ('bylaws_final', 'Final By-laws')], max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('document_generated', models.BooleanField(default=False)),
                ('document_uploaded', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='society.case')),
            ],
            options={
                'unique_together': {('case', 'stage_code')},
            },
        ),
        migrations.AddConstraint(
            model_name='flatownership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('flat',), name='one_active_ownership_per_flat'),
        ),
        migrations.AddConstraint(
            model_name='flatowner',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('legal_entity_name__isnull', False), _connector='OR'), name='flatowner_requires_person_or_entity'),
        ),
        migrations.AlterUniqueTogether(
            name='flatmaintenancebill',
            unique_together={('bill', 'flat')},
        ),
        migrations.AlterUniqueTogether(
            name='maintenancebill',
            unique_together={('society', 'billing_month')},
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together={('society', 'flat_number')},
        ),
        migrations.AlterUniqueTogether(
            name='chartofaccount',
            unique_together={('society', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='amenity',
            unique_together={('society', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='accountingperiod',
            unique_together={('society', 'start_date', 'end_date')},
        ),
        migrations.AlterUniqueTogether(
            name='societychargerule',
            unique_together={('society', 'charge_type', 'effective_from')},
        ),
        migrations.AlterUniqueTogether(
            name='transactionrule',
            unique_together={('society', 'transaction_type')},
        ),
    ]
