# Generated by Django 5.2.7 on 2025-12-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('registration_no', models.CharField(blank=True, max_length=100)),
                ('date_of_registration', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
