# Generated by Django 5.2.7 on 2025-12-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='legal_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROCESS', 'In Process'), ('LEGALLY_COMPLETE', 'Legally Complete')], default='DRAFT', max_length=30),
        ),
    ]
