# Generated by Django 5.2.7 on 2026-02-26 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyOfficeBearer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CHAIRMAN', 'Chairman'), ('SECRETARY', 'Secretary'), ('TREASURER', 'Treasurer'), ('COMMITTEE_MEMBER', 'Committee Member')], db_index=True, max_length=30)),
                ('appointed_on', models.DateField(blank=True, help_text='Date when the role was assigned', null=True)),
                ('term_end', models.DateField(blank=True, help_text='End of office term', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_bearers', to='society.society')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-appointed_on', '-created_at'],
                'indexes': [models.Index(fields=['society', 'role', 'is_active'], name='society_soc_society_794f7a_idx')],
            },
        ),
    ]
