# Generated by Django 5.2.7 on 2026-01-03 05:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_society_legal_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('acquired_on', models.DateField(default=django.utils.timezone.now)),
                ('relinquished_on', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_ownerships', to='society.society')),
            ],
            options={
                'ordering': ['-acquired_on'],
                'indexes': [models.Index(fields=['society', 'is_active'], name='society_sha_society_cbb2ea_idx')],
            },
        ),
    ]
