# Generated by Django 5.2.7 on 2026-02-27 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_wing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='society.wing')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('wing', 'number')},
            },
        ),
    ]
