# Generated by Django 5.2.7 on 2026-01-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_shareownership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShareOwnership',
        ),
    ]
