# Generated by Django 5.2.7 on 2026-02-27 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0004_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='floor_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flat_records', to='society.floor'),
        ),
        migrations.AddField(
            model_name='flat',
            name='wing_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flat_records', to='society.wing'),
        ),
    ]
