# Generated by Django 5.2.7 on 2026-01-05 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0004_delete_shareownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(help_text='Flat number as per society records (e.g. A-101, 1203)', max_length=20)),
                ('wing', models.CharField(blank=True, help_text='Wing / building identifier (if applicable)', max_length=20, null=True)),
                ('floor', models.IntegerField(blank=True, help_text='Floor number', null=True)),
                ('carpet_area_sqft', models.DecimalField(blank=True, decimal_places=2, help_text='Carpet area in square feet', max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this flat is active (not merged / demolished)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='society.society')),
            ],
            options={
                'ordering': ['flat_number'],
                'unique_together': {('society', 'flat_number')},
            },
        ),
        migrations.CreateModel(
            name='FlatOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_on', models.DateField()),
                ('relinquished_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='society.flat')),
            ],
            options={
                'ordering': ['-acquired_on'],
            },
        ),
        migrations.CreateModel(
            name='FlatOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_entity_name', models.CharField(blank=True, help_text='Company / Trust / Entity name (if applicable)', max_length=255, null=True)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, help_text='Ownership percentage (e.g. 50.00)', max_digits=5)),
                ('user', models.ForeignKey(blank=True, help_text='Linked user account (if individual)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='society.flatownership')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('user__isnull', False), ('legal_entity_name__isnull', False), _connector='OR'), name='flatowner_requires_person_or_entity')],
            },
        ),
    ]
