# Generated by Django 5.2.7 on 2026-02-27 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0005_flat_floor_ref_flat_wing_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('REGULAR', 'Regular Member'), ('ASSOCIATE', 'Associate Member'), ('NOMINAL', 'Nominal Member'), ('PROVISIONAL', 'Provisional Member'), ('INSTITUTIONAL', 'Institutional Member')], max_length=30)),
                ('member_number', models.CharField(max_length=50)),
                ('admitted_on', models.DateField()),
                ('ceased_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_memberships', to='society.person')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='society.society')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('society', 'member_number'), name='unique_member_number_per_society')],
                'unique_together': {('society', 'person')},
            },
        ),
    ]
