# Generated by Django 5.2.7 on 2026-02-27 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0006_societymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elected_on', models.DateField()),
                ('term_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to='society.societymember')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to='society.society')),
            ],
            options={
                'ordering': ['-elected_on'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('society', 'member'), name='unique_active_committee_member_per_society')],
            },
        ),
    ]
