# Generated by Django 5.2.7 on 2026-02-27 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0007_committeemembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='societyofficebearer',
            name='committee_membership_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_office_bearers', to='society.committeemembership'),
        ),
    ]
