# Generated by Django 5.2.7 on 2026-01-05 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0007_amenity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=50)),
                ('parking_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('VISITOR', 'Visitor')], max_length=20)),
                ('allocation_type', models.CharField(choices=[('FLAT', 'Flat Allotted'), ('MEMBER', 'Member Allotted'), ('COMMON', 'Common Use')], default='COMMON', max_length=20)),
                ('is_chargeable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_slots', to='society.society')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_on', models.DateField()),
                ('released_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_allocations', to='society.flat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_allocations', to=settings.AUTH_USER_MODEL)),
                ('parking_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='society.parkingslot')),
            ],
        ),
    ]
