# Generated by Django 5.2.7 on 2026-02-27 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0009_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='society',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formation_case', to='society.society'),
        ),
    ]
