# Generated by Django 5.2.7 on 2026-01-06 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0009_remove_amenity_charge_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityChargeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('FREE', 'Free'), ('FIXED', 'Fixed Monthly'), ('PER_USE', 'Per Use'), ('PER_FLAT', 'Per Flat')], default='FREE', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly or per-use amount', max_digits=10, null=True)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('amenity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charge_rule', to='society.amenity')),
            ],
            options={
                'ordering': ['effective_from'],
            },
        ),
    ]
