# Generated by Django 5.2.7 on 2026-01-06 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0010_amenitychargerule'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy_type', models.CharField(choices=[('SELF', 'Self Occupied'), ('RENTED', 'Rented / Leave & License'), ('FAMILY', 'Occupied by Family'), ('VACANT', 'Vacant / Locked'), ('CORPORATE', 'Corporate Occupancy')], default='SELF', max_length=20)),
                ('declared_on', models.DateField(auto_now=True)),
                ('flat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy', to='society.flat')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_paid_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CLEAR', 'No Dues'), ('OVERDUE', 'Overdue'), ('NOTICE_SENT', 'Notice Issued'), ('RESOLUTION_PASSED', 'Resolution Passed'), ('LEGAL', 'Legal Recovery')], default='CLEAR', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_account', to='society.flat')),
            ],
        ),
    ]
