# Generated by Django 5.2.7 on 2026-02-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0010_case_society'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='registration_number',
            field=models.CharField(blank=True, db_index=True, help_text='Official society registration number issued by Registrar', max_length=50, null=True, unique=True),
        ),
    ]
