# Generated by Django 5.2.7 on 2026-02-28 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0011_alter_society_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftOnboardingTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soft_onboarding_tracker', to='society.society')),
            ],
        ),
    ]
