# Generated by Django 5.2.7 on 2026-03-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0012_softonboardingtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='flat_type',
            field=models.CharField(blank=True, help_text='Flat configuration such as 1BHK, 2BHK, 3BHK', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.IntegerField(blank=True, help_text='Floor number (legacy support)', null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='wing',
            field=models.CharField(blank=True, help_text='Wing / building identifier (legacy support)', max_length=20, null=True),
        ),
    ]
