# Generated by Django 5.2.7 on 2026-01-06 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0012_chargetype_maintenanceaccount_balance_due_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField(help_text='First day of the billing month')),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_bills', to='society.society')),
            ],
            options={
                'ordering': ['-billing_month'],
                'unique_together': {('society', 'billing_month')},
            },
        ),
        migrations.CreateModel(
            name='FlatMaintenanceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('non_occupancy_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.flat')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_bills', to='society.maintenancebill')),
            ],
            options={
                'unique_together': {('bill', 'flat')},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='society.flatmaintenancebill')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='society.flat')),
            ],
        ),
    ]
