# Generated by Django 5.2.7 on 2026-01-06 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0013_maintenancebill_flatmaintenancebill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('ONLINE', 'Online Gateway')], max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Cheque no / UTR / Txn ID', max_length=100, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('CLEARED', 'Cleared'), ('BOUNCED', 'Bounced'), ('REVERSED', 'Reversed')], default='RECEIVED', max_length=20)),
                ('received_on', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, help_text='Null if advance or miscellaneous payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='society.maintenancebill')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='society.flat')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='society.society')),
            ],
            options={
                'ordering': ['-received_on', '-created_at'],
            },
        ),
    ]
