# Generated by Django 5.2.7 on 2026-03-05 17:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0013_flat_flat_type_alter_flat_floor_alter_flat_wing'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='flatowner',
            name='flatowner_requires_person_or_entity',
        ),
        migrations.RemoveField(
            model_name='flatowner',
            name='user',
        ),
        migrations.AddField(
            model_name='flatowner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flatowner',
            name='person',
            field=models.ForeignKey(blank=True, help_text='Individual person owner (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flat_ownerships', to='society.person'),
        ),
        migrations.AlterField(
            model_name='flatowner',
            name='legal_entity_name',
            field=models.CharField(blank=True, help_text='Company / Trust / Legal entity owner (if applicable)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flatowner',
            name='ownership_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Ownership percentage (must total 100% per flat)', max_digits=5),
        ),
        migrations.AddConstraint(
            model_name='flatowner',
            constraint=models.CheckConstraint(condition=models.Q(('person__isnull', False), ('legal_entity_name__isnull', False), _connector='OR'), name='flatowner_requires_person_or_entity'),
        ),
        migrations.AddConstraint(
            model_name='flatowner',
            constraint=models.UniqueConstraint(fields=('ownership', 'person'), name='unique_owner_per_flat'),
        ),
    ]
