# Generated by Django 5.2.7 on 2026-03-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0014_remove_flatowner_flatowner_requires_person_or_entity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartofaccount',
            options={'ordering': ['account_type', 'code']},
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='code',
            field=models.CharField(help_text='Short account code (e.g. MAINT, BANK, SINKFUND)', max_length=20),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System-generated account (cannot be deleted)'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='name',
            field=models.CharField(help_text='Account name', max_length=255),
        ),
    ]
