# Generated by Django 5.2.7 on 2026-03-11 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0016_accountgroup_chartofaccount_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('basis', models.CharField(choices=[('EQUAL', 'Equal Per Flat'), ('AREA', 'Per Square Foot'), ('PER_SLOT', 'Per Parking Slot'), ('PER_INLET', 'Per Water Inlet'), ('PERCENT_MAINT', '% of Maintenance')], max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_charges', to='society.society')),
            ],
        ),
    ]
