# Generated by Django 5.2.7 on 2026-01-08 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('society', '0014_payment'),
]


    operations = [
        migrations.CreateModel(
            name='SocietyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('INTEREST', 'Interest'), ('NON_OCCUPANCY', 'Non Occupancy Charge'), ('LATE_FEE', 'Late Fee')], max_length=30)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percentage rate (e.g. 10.00 for 10%)', max_digits=6)),
                ('cap_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum cap if applicable', max_digits=6, null=True)),
                ('applies_after_days', models.PositiveIntegerField(default=0, help_text='Grace period before rule applies')),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.society')),
            ],
        ),
    ]
