# Generated by Django 5.2.7 on 2026-03-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0017_maintenancecharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancecharge',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
