# Generated by Django 5.2.7 on 2026-01-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0018_noticelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticelog',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
