# Generated by Django 5.2.7 on 2026-03-11 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0018_alter_maintenancecharge_effective_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatmaintenancebill',
            name='charge_breakdown',
            field=models.JSONField(default=list, help_text='Detailed charge breakdown for the bill'),
        ),
        migrations.AddField(
            model_name='flatmaintenancebill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
