# Generated by Django 5.2.7 on 2026-01-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0019_noticelog_interest_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticelog',
            name='notice_type',
            field=models.CharField(choices=[('REMINDER', 'Reminder'), ('DEMAND', 'Demand'), ('FINAL', 'Final Notice'), ('LEGAL', 'Legal Notice')], max_length=20),
        ),
        migrations.AlterField(
            model_name='noticelog',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='noticelog',
            name='reference_period',
            field=models.CharField(max_length=50),
        ),
    ]
