# Generated by Django 5.2.7 on 2026-03-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0019_flatmaintenancebill_charge_breakdown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatmaintenancebill',
            name='charge_breakdown',
        ),
    ]
