# Generated by Django 5.2.7 on 2026-03-11 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0020_remove_flatmaintenancebill_charge_breakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatMaintenanceBillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_code', models.CharField(max_length=50)),
                ('charge_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='society.flatmaintenancebill')),
            ],
        ),
    ]
