# Generated by Django 5.2.7 on 2026-01-08 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0020_alter_noticelog_notice_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatRecoveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('NONE', 'No Recovery'), ('REMINDER', 'Reminder Issued'), ('DEMAND', 'Demand Notice'), ('FINAL', 'Final Notice'), ('REGISTRAR', 'Filed with Registrar'), ('LEGAL', 'Legal Proceedings'), ('CLOSED', 'Recovered / Closed')], default='NONE', max_length=20)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_action_on', models.DateField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('flat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_status', to='society.flat')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('NONE', 'No Recovery'), ('REMINDER', 'Reminder Issued'), ('DEMAND', 'Demand Notice'), ('FINAL', 'Final Notice'), ('REGISTRAR', 'Filed with Registrar'), ('LEGAL', 'Legal Proceedings'), ('CLOSED', 'Recovered / Closed')], max_length=20)),
                ('action_date', models.DateField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, help_text='Notice number / Registrar file no / etc', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_actions', to='society.flat')),
            ],
        ),
    ]
