# Generated by Django 5.2.7 on 2026-03-11 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0021_flatmaintenancebillline'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable', to='society.flatmaintenancebill')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.flat')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.society')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.flat')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='society.memberreceivable')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.society')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.society')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='society.paymenttransaction')),
            ],
        ),
    ]
