# Generated by Django 5.2.7 on 2026-01-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0023_chartofaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartofaccount',
            options={},
        ),
        migrations.RemoveField(
            model_name='chartofaccount',
            name='is_active',
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System-generated account (do not delete)'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('RESERVE', 'Reserve')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
