# Generated by Django 5.2.7 on 2026-03-11 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0023_notificationevent_vendor_vendorbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount of the bill', max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, help_text='Remaining unpaid amount', max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payables', to='society.society')),
                ('vendor_bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payable', to='society.vendorbill')),
            ],
        ),
    ]
