# Generated by Django 5.2.7 on 2026-03-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0025_vendorpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='district',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
