# Generated by Django 5.2.7 on 2026-01-09 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0025_ledgerentry_delete_maintenanceledgerentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='credit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='society.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='debit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_entries', to='society.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='society.flat'),
        ),
    ]
