# Generated by Django 5.2.7 on 2026-01-09 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0026_alter_ledgerentry_credit_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(help_text='Must match a TransactionType value', max_length=50)),
                ('debit_account_code', models.CharField(max_length=30)),
                ('credit_account_code', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_rules', to='society.society')),
            ],
            options={
                'unique_together': {('society', 'transaction_type')},
            },
        ),
    ]
