# Generated by Django 5.2.7 on 2026-03-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0026_society_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='onboarding_stage',
            field=models.CharField(choices=[('STRUCTURE_PENDING', 'Structure Pending'), ('STRUCTURE_CREATED', 'Structure Created'), ('OWNERSHIP_PENDING', 'Ownership Pending'), ('ONBOARDING_COMPLETE', 'Onboarding Complete')], default='STRUCTURE_PENDING', max_length=50),
        ),
    ]
