# Generated by Django 5.2.7 on 2026-01-09 21:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0027_transactionrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionrule',
            name='notes',
        ),
        migrations.AddField(
            model_name='transactionrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionrule',
            name='credit_account_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionrule',
            name='debit_account_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionrule',
            name='transaction_type',
            field=models.CharField(choices=[('MAINTENANCE_RECEIPT', 'MAINTENANCE_RECEIPT'), ('MAINTENANCE_BILL', 'MAINTENANCE_BILL'), ('ELECTRICITY_BILL_PAYMENT', 'ELECTRICITY_BILL_PAYMENT'), ('SALARY_PAYMENT', 'SALARY_PAYMENT'), ('BANK_DEPOSIT', 'BANK_DEPOSIT'), ('BANK_WITHDRAWAL', 'BANK_WITHDRAWAL'), ('FD_CREATION', 'FD_CREATION'), ('FD_INTEREST_RECEIVED', 'FD_INTEREST_RECEIVED'), ('PENALTY_CHARGED', 'PENALTY_CHARGED')], max_length=50),
        ),
    ]
