# Generated by Django 5.2.7 on 2026-01-11 11:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0028_remove_transactionrule_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerentry',
            name='credit_amount',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='debit_amount',
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='amount',
            field=models.DecimalField(
            max_digits=14,
            decimal_places=2,
            null=True,      # ✅ inside the field
            blank=True,     # ✅ inside the field
            ),
        ),

        migrations.AddField(
            model_name='ledgerentry',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='source_ref',
            field=models.CharField(blank=True, help_text='External reference ID', max_length=100),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='source_type',
            field=models.CharField(blank=True, help_text='BILL / PAYMENT / ADJUSTMENT / OPENING', max_length=50),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='credit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='society.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='debit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_entries', to='society.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='transactionrule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
