# Generated by Django 5.2.7 on 2026-01-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0029_remove_ledgerentry_credit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
