# Generated by Django 5.2.7 on 2026-03-30 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0029_alter_societyofficebearer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='societyofficebearer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('society', 'role'), name='unique_active_role_per_society'),
        ),
    ]
