# Generated by Django 5.2.7 on 2026-03-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0030_societyofficebearer_unique_active_role_per_society'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='onboarding_stage',
            field=models.CharField(choices=[('STRUCTURE_PENDING', 'Structure Pending'), ('STRUCTURE_CREATED', 'Structure Created'), ('OWNERSHIP_PENDING', 'Ownership Pending'), ('ONBOARDING_COMPLETE', 'Onboarding Complete'), ('OPERATIONS_PENDING', 'Operations Pending'), ('OPERATIONS_COMPLETE', 'Operations Complete'), ('FINANCIAL_PENDING', 'Financial Pending'), ('FINANCIAL_COMPLETE', 'Financial Complete'), ('SYSTEM_LIVE', 'System Live')], default='STRUCTURE_PENDING', max_length=50),
        ),
    ]
