# Generated by Django 5.2.7 on 2026-01-11 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0031_accountingperiod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('MAINTENANCE_RECEIPT', 'MAINTENANCE_RECEIPT'), ('MAINTENANCE_BILL', 'MAINTENANCE_BILL'), ('ELECTRICITY_BILL_PAYMENT', 'ELECTRICITY_BILL_PAYMENT'), ('SALARY_PAYMENT', 'SALARY_PAYMENT'), ('BANK_DEPOSIT', 'BANK_DEPOSIT'), ('BANK_WITHDRAWAL', 'BANK_WITHDRAWAL'), ('FD_CREATION', 'FD_CREATION'), ('FD_INTEREST_RECEIVED', 'FD_INTEREST_RECEIVED'), ('PENALTY_CHARGED', 'PENALTY_CHARGED')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField()),
                ('entry_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_transactions', to='society.society')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
