# Generated by Django 5.2.7 on 2026-03-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0031_alter_society_onboarding_stage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='committee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('society',), name='unique_active_committee_per_society'),
        ),
    ]
