# Generated by Django 5.2.7 on 2026-04-13 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0032_committee_unique_active_committee_per_society'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('share_count', models.PositiveIntegerField()),
                ('share_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_certificates', to='statutory.societylegaldocument')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_certificates', to='society.flat')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_certificates', to='society.society')),
            ],
            options={
                'ordering': ['flat'],
                'unique_together': {('society', 'flat')},
            },
        ),
    ]
