# Generated by Django 5.2.7 on 2026-04-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0033_sharecertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharecertificate',
            name='share_number_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharecertificate',
            name='share_number_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
