# Generated by Django 5.2.7 on 2026-04-15 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0034_sharecertificate_share_number_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_spend_without_approval', models.DecimalField(blank=True, decimal_places=2, help_text='Max amount allowed without approval', max_digits=12, null=True)),
                ('approval_required_above', models.DecimalField(blank=True, decimal_places=2, help_text='Amount above which approval is required', max_digits=12, null=True)),
                ('approval_authority', models.CharField(choices=[('COMMITTEE', 'Committee'), ('DUAL_COMMITTEE', 'Dual Committee Approval'), ('GENERAL_BODY', 'General Body (AGM/SGM)')], default='COMMITTEE', max_length=20)),
                ('committee_approval_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Max amount committee can approve', max_digits=12, null=True)),
                ('member_approval_required_above', models.DecimalField(blank=True, decimal_places=2, help_text='Amount above which general body approval is required', max_digits=12, null=True)),
                ('approval_mode', models.CharField(choices=[('SINGLE', 'Single Approval'), ('DUAL', 'Dual Approval'), ('FULL_COMMITTEE', 'Full Committee Approval')], default='SINGLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operational_rule', to='society.society')),
            ],
        ),
    ]
