# Generated by Django 5.2.7 on 2026-04-17 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0035_operationalrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='MONTHLY', max_length=20)),
                ('due_day', models.IntegerField(default=10)),
                ('grace_days', models.IntegerField(default=5)),
                ('charges', models.JSONField(blank=True, default=list)),
                ('interest_rules', models.JSONField(blank=True, default=dict)),
                ('penalty_rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_rule', to='society.society')),
            ],
        ),
    ]
