# Generated by Django 5.2.7 on 2026-01-15 18:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0035_alter_auditevent_options_auditevent_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='action',
            field=models.CharField(default='SYSTEM_MIGRATION', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor_role',
            field=models.CharField(default='SYSTEM', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditevent',
            name='event_hash',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(default='MIGRATION', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='object_id',
            field=models.CharField(default='MIGRATION', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditevent',
            name='object_type',
            field=models.CharField(default='SYSTEM', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditevent',
            name='payload',
            field=models.JSONField(default=dict),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditevent',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
