# Generated by Django 5.2.7 on 2026-04-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0036_billingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrule',
            name='billing_start_date',
            field=models.DateField(blank=True, help_text='Date from which billing should start for the society', null=True),
        ),
    ]
