# Generated by Django 5.2.7 on 2026-01-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0036_auditevent_action_auditevent_actor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit Event', 'verbose_name_plural': 'Audit Events'},
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='action',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='actor_role',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='event_hash',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='previous_hash',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='domain',
            field=models.CharField(default='legacy', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='object_type',
            field=models.CharField(max_length=64),
        ),
    ]
