# Generated by Django 5.2.7 on 2026-01-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0037_alter_auditevent_options_remove_auditevent_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='event_hash',
            field=models.CharField(db_index=True, default='GENESIS', editable=False, max_length=64),
            preserve_default=False,
        ),
    ]
