# Generated by Django 5.2.7 on 2026-04-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0037_billingrule_billing_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalrule',
            name='billing_target',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('TENANT', 'Tenant'), ('BOTH', 'Both')], default='OWNER', max_length=20),
        ),
        migrations.AddField(
            model_name='operationalrule',
            name='dispute_apply_interest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='operationalrule',
            name='dispute_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operationalrule',
            name='dispute_hold_bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operationalrule',
            name='manager_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operationalrule',
            name='vacant_type',
            field=models.CharField(choices=[('FULL', 'Full Charges'), ('REDUCED', 'Reduced Charges'), ('NONE', 'No Charges')], default='FULL', max_length=20),
        ),
        migrations.AddField(
            model_name='operationalrule',
            name='vacant_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationalrule',
            name='waiver_authority',
            field=models.CharField(choices=[('COMMITTEE', 'Committee'), ('CHAIRMAN', 'Chairman'), ('TREASURER', 'Treasurer')], default='COMMITTEE', max_length=20),
        ),
    ]
