# Generated by Django 5.2.7 on 2026-04-20 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0038_operationalrule_billing_target_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('aadhaar_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('appointed_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='society.society')),
                ('user', models.OneToOneField(blank=True, help_text='Linked platform user account for manager access', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
