# Generated by Django 5.2.7 on 2026-01-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0038_auditevent_event_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='previous_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True),
        ),
    ]
