# Generated by Django 5.2.7 on 2026-04-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0039_societymanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalrule',
            name='financial_controls_configured',
            field=models.BooleanField(default=False, help_text='Set to True when financial controls (SCR19) are completed'),
        ),
    ]
