# Generated by Django 5.2.7 on 2026-01-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0039_auditevent_previous_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='previous_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
