# Generated by Django 5.2.7 on 2026-01-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0040_alter_auditevent_previous_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceMemoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('node_id', models.CharField(max_length=128)),
                ('workflow_id', models.CharField(blank=True, max_length=128, null=True)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['node_id'], name='society_int_node_id_7bd56b_idx'), models.Index(fields=['workflow_id'], name='society_int_workflo_ee7942_idx'), models.Index(fields=['event_type'], name='society_int_event_t_daa663_idx')],
            },
        ),
    ]
