# Generated by Django 5.2.7 on 2026-04-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0040_operationalrule_financial_controls_configured'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalrule',
            name='max_cash_spend_allowed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount allowed for cash transactions', max_digits=12, null=True),
        ),
    ]
