# Generated by Django 5.2.7 on 2026-04-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0041_operationalrule_max_cash_spend_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='authorized_share_capital',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum share capital the society is authorized to raise', max_digits=14, null=True),
        ),
    ]
