# Generated by Django 5.2.7 on 2026-02-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0041_intelligencememoryevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='state_code',
            field=models.CharField(default='MH', help_text='Legal jurisdiction state code (MH, KA, DL, etc.)', max_length=10),
        ),
    ]
