# Generated by Django 5.2.7 on 2026-02-16 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0044_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_code', models.CharField(choices=[('member_list', 'Member List'), ('share_structure', 'Share Structure'), ('entrance_fees', 'Entrance Fees'), ('promoter_affidavit', 'Promoter Affidavit'), ('bank_account', 'Bank Account'), ('building_docs', 'Building Documents'), ('oc_cc', 'OC / CC'), ('land_docs', 'Land Documents'), ('builder_noc', 'Builder NOC'), ('society_resolution', 'Society Resolution'), ('bylaws_final', 'Final By-laws')], max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('document_generated', models.BooleanField(default=False)),
                ('document_uploaded', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='society.case')),
            ],
            options={
                'unique_together': {('case', 'stage_code')},
            },
        ),
    ]
