# Generated by Django 5.2.7 on 2026-05-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0048_add_registration_cert_fields'),
    ]

    operations = [

        migrations.AddField(
            model_name='bankaccount',
            name='upi_id',
            field=models.CharField(
                max_length=100,
                blank=True,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='bankaccount',
            name='banking_phone',
            field=models.CharField(
                max_length=20,
                blank=True,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='bankaccount',
            name='banking_email',
            field=models.EmailField(
                max_length=254,
                blank=True,
                null=True,
            ),
        ),

    ]
