# Generated by Django 5.2.7 on 2026-05-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0049_add_banking_identity_fields'),
    ]

    operations = [

        migrations.AddField(
            model_name='bankaccount',
            name='treasury_role',
            field=models.CharField(
                max_length=30,
                choices=[
                    ('OPERATIONS', 'Operations'),
                    ('SINKING_FUND', 'Sinking Fund'),
                    ('RESERVE', 'Reserve'),
                    ('FD', 'Fixed Deposit'),
                ],
                default='OPERATIONS',
            ),
        ),

        migrations.AddField(
            model_name='bankaccount',
            name='bank_address',
            field=models.TextField(
                blank=True,
                null=True,
            ),
        ),

    ]