# Generated by Django 5.2.7 on 2026-05-25 10:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "society",
            "0051_auto_20260516_1404",
        ),
    ]

    operations = [

        migrations.AlterField(

            model_name="parkingslot",

            name="parking_type",

            field=models.CharField(

                max_length=20,

                choices=[

                    ("CAR", "Car"),

                    ("BIKE", "Bike"),

                    ("EV", "EV"),

                    ("VISITOR", "Visitor"),
                ],
            ),
        ),
    ]