# Generated by Django 5.2.7 on 2026-05-28 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            'society',
            '0052_expand_parking_type_for_ev_support',
        ),
    ]

    operations = [

        migrations.CreateModel(

            name='ParkingRateConfiguration',

            fields=[

                (
                    'id',

                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),

                (
                    'parking_type',

                    models.CharField(
                        choices=[
                            ('CAR', 'Four Wheeler'),
                            ('BIKE', 'Two Wheeler'),
                            ('EV', 'EV Vehicle'),
                            ('VISITOR', 'Visitor Parking'),
                        ],
                        max_length=20,
                    ),
                ),

                (
                    'rate',

                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                    ),
                ),

                (
                    'is_active',

                    models.BooleanField(
                        default=True,
                    ),
                ),

                (
                    'created_at',

                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),

                (
                    'society',

                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='parking_rate_configurations',
                        to='society.society',
                    ),
                ),
            ],

            options={

                'unique_together': {
                    (
                        'society',
                        'parking_type',
                    ),
                },
            },
        ),
    ]