# Generated by Django 5.2.7 on 2026-06-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0053_add_parking_rate_configuration'),
    ]

    operations = [

        migrations.AddField(
            model_name='maintenancebill',
            name='bill_number',
            field=models.CharField(
                max_length=100,
                null=True,
                blank=True,
            ),
        ),

        migrations.AddField(
            model_name='maintenancebill',
            name='bill_date',
            field=models.DateField(
                null=True,
                blank=True,
            ),
        ),

        migrations.AddField(
            model_name='maintenancebill',
            name='due_date',
            field=models.DateField(
                null=True,
                blank=True,
            ),
        ),

    ]