# Generated by Django 5.2.7 on 2026-07-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("society", "0054_add_bill_metadata_to_maintenance_bill"),
    ]

    operations = [

        migrations.AddField(

            model_name="society",

            name="official_email",

            field=models.EmailField(
                blank=True,
                null=True,
                max_length=254,
                help_text="Official communication email for the society",
            ),

        ),

        migrations.AddField(

            model_name="society",

            name="communications_enabled",

            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the SocietyOS communications engine has been activated",
            ),

        ),

    ]