# Generated by Django 5.2.7 on 2026-07-13 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("society", "0055_add_society_communications_fields"),
    ]

    operations = [

        migrations.CreateModel(

            name="ExpenseAuthorization",

            fields=[

                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),

                (
                    "expense_category",
                    models.CharField(
                        max_length=100,
                    ),
                ),

                (
                    "purpose",
                    models.TextField(),
                ),

                (
                    "estimated_amount",
                    models.DecimalField(
                        max_digits=12,
                        decimal_places=2,
                    ),
                ),

                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                    ),
                ),

                (
                    "status",
                    models.CharField(
                        max_length=40,
                        default="DRAFT",
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("WORK_ORDER_ISSUED", "Work Order Issued"),
                            ("GOODS_OR_SERVICES_RECEIVED", "Goods / Services Received"),
                            ("INVOICE_RECEIVED", "Invoice Received"),
                            ("INVOICE_BOOKED", "Invoice Booked"),
                            ("PAYMENT_AUTHORIZED", "Payment Authorized"),
                            ("PAID", "Paid"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                    ),
                ),

                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),

                (
                    "society",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_authorizations",
                        to="society.society",
                    ),
                ),

            ],

        ),

    ]