"""
==========================================================
SCR35-002

Synchronize the ExpenseAuthorization database schema
with the finalized governance domain model.

0056 introduced the ExpenseAuthorization root entity.

During architectural review, three governance fields
were confirmed as permanent business truth:

• approval_reference
• approval_date
• funding_source

This migration adds those fields without altering
the original migration history.
==========================================================
"""

# Generated by Django 5.2.7 on 2026-07-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("society", "0056_create_expense_authorization"),
    ]

    operations = [

        migrations.AddField(

            model_name="expenseauthorization",

            name="approval_reference",

            field=models.CharField(
                max_length=100,
                blank=True,
                null=True,
            ),

        ),

        migrations.AddField(

            model_name="expenseauthorization",

            name="approval_date",

            field=models.DateField(
                blank=True,
                null=True,
            ),

        ),

        migrations.AddField(

            model_name="expenseauthorization",

            name="funding_source",

            field=models.CharField(
                max_length=100,
                blank=True,
                null=True,
            ),

        ),

    ]