"""
==========================================================
SCR35-003

Links Vendor Bills to their originating
Expense Authorization.

This establishes the permanent relationship
between Governance and Finance.

One Expense Authorization may produce many
Vendor Bills over its lifecycle.

Deletion of an Expense Authorization is
protected once Vendor Bills exist, preserving
financial audit integrity.
==========================================================
"""

# Generated by Django 5.2.7 on 2026-07-13 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("society", "0057_sync_expense_authorization_fields"),
    ]

    operations = [

        migrations.AddField(

            model_name="vendorbill",

            name="expense_authorization",

            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendor_bills",
                to="society.expenseauthorization",
                null=True,
                blank=True,
            ),

        ),

    ]