# Generated by Django 5.2.7

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("society", "0058_link_vendor_bill_to_expense_authorization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        # ======================================================
        # Procurement Identity
        # ======================================================

        migrations.AddField(
            model_name="expenseauthorization",
            name="procurement_reference",
            field=models.CharField(
                max_length=30,
                unique=True,
                blank=True,
                null=True,
                editable=False,
                help_text=(
                    "Immutable business reference for the "
                    "entire procurement lifecycle."
                ),
            ),
        ),

        # ======================================================
        # Procurement Instrument
        # ======================================================

        migrations.AddField(
            model_name="expenseauthorization",
            name="procurement_document_type",
            field=models.CharField(
                max_length=30,
                choices=[
                    ("WORK_ORDER", "Work Order"),
                    ("PURCHASE_ORDER", "Purchase Order"),
                    ("SERVICE_REQUEST", "Service Request"),
                ],
                blank=True,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="expenseauthorization",
            name="procurement_document_number",
            field=models.CharField(
                max_length=100,
                blank=True,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="expenseauthorization",
            name="procurement_document_date",
            field=models.DateField(
                blank=True,
                null=True,
            ),
        ),

        # ======================================================
        # Execution Evidence
        # ======================================================

        migrations.AddField(
            model_name="expenseauthorization",
            name="completion_date",
            field=models.DateField(
                blank=True,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="expenseauthorization",
            name="goods_receipt_reference",
            field=models.CharField(
                max_length=100,
                blank=True,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="expenseauthorization",
            name="goods_receipt_date",
            field=models.DateField(
                blank=True,
                null=True,
            ),
        ),

        # ======================================================
        # Payment Governance
        # ======================================================

        migrations.AddField(
            model_name="expenseauthorization",
            name="payment_authorization_reference",
            field=models.CharField(
                max_length=100,
                blank=True,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="expenseauthorization",
            name="payment_authorization_date",
            field=models.DateField(
                blank=True,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="expenseauthorization",
            name="payment_authorized_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authorized_expense_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        # ======================================================
        # Closure Governance
        # ======================================================

        migrations.AddField(
            model_name="expenseauthorization",
            name="closed_date",
            field=models.DateField(
                blank=True,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="expenseauthorization",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_expense_authorizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        migrations.AddField(
            model_name="expenseauthorization",
            name="closure_notes",
            field=models.TextField(
                blank=True,
                null=True,
            ),
        ),

    ]