# Generated by Django 5.2.7 on 2026-07-16

from django.db import migrations


def normalize_procurement_terminology(
    apps,
    schema_editor,
):
    ExpenseAuthorization = apps.get_model(
        "society",
        "ExpenseAuthorization",
    )

    procurement_type_map = {
        "WORK_ORDER": "WORKS",
        "PURCHASE_ORDER": "GOODS",
        "SERVICE_REQUEST": "SERVICES",
    }

    status_map = {
        "WORK_ORDER_ISSUED": (
            "PROCUREMENT_DOCUMENT_ISSUED"
        ),
        "GOODS_OR_SERVICES_RECEIVED": (
            "PROCUREMENT_COMPLETED"
        ),
    }

    for authorization in (
        ExpenseAuthorization.objects.all()
    ):

        update_fields = []

        if (
            authorization.procurement_type
            in procurement_type_map
        ):

            authorization.procurement_type = (
                procurement_type_map[
                    authorization.procurement_type
                ]
            )

            update_fields.append(
                "procurement_type"
            )

        if (
            authorization.status
            in status_map
        ):

            authorization.status = (
                status_map[
                    authorization.status
                ]
            )

            update_fields.append(
                "status"
            )

        if update_fields:

            authorization.save(
                update_fields=update_fields,
            )


def reverse_normalize_procurement_terminology(
    apps,
    schema_editor,
):
    ExpenseAuthorization = apps.get_model(
        "society",
        "ExpenseAuthorization",
    )

    procurement_type_map = {
        "WORKS": "WORK_ORDER",
        "GOODS": "PURCHASE_ORDER",
        "SERVICES": "SERVICE_REQUEST",
    }

    status_map = {
        "PROCUREMENT_DOCUMENT_ISSUED": (
            "WORK_ORDER_ISSUED"
        ),
        "PROCUREMENT_COMPLETED": (
            "GOODS_OR_SERVICES_RECEIVED"
        ),
    }

    for authorization in (
        ExpenseAuthorization.objects.all()
    ):

        update_fields = []

        if (
            authorization.procurement_type
            in procurement_type_map
        ):

            authorization.procurement_type = (
                procurement_type_map[
                    authorization.procurement_type
                ]
            )

            update_fields.append(
                "procurement_type"
            )

        if (
            authorization.status
            in status_map
        ):

            authorization.status = (
                status_map[
                    authorization.status
                ]
            )

            update_fields.append(
                "status"
            )

        if update_fields:

            authorization.save(
                update_fields=update_fields,
            )


class Migration(migrations.Migration):

    dependencies = [
        (
            "society",
            "0059_complete_expense_authorization_aggregate",
        ),
    ]

    operations = [

        migrations.RenameField(
            model_name="expenseauthorization",
            old_name="procurement_document_type",
            new_name="procurement_type",
        ),

        migrations.RunPython(
            normalize_procurement_terminology,
            reverse_normalize_procurement_terminology,
        ),

    ]
