# Generated by Django 5.2.7 on 2026-07-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("society", "0060_normalize_procurement_terminology"),
    ]

    operations = [

        # ==========================================================
        # STEP 1
        # Introduce immutable canonical system account identity.
        #
        # This identity is consumed by SocietyOS financial engines
        # instead of relying on account names or display codes.
        # ==========================================================

        migrations.AddField(
            model_name="chartofaccount",
            name="system_account",
            field=models.CharField(
                max_length=60,
                null=True,
                blank=True,
                choices=[
                    ("BANK_OPERATIONS", "Bank - Operations"),
                    ("BANK_SINKING_FUND", "Bank - Sinking Fund"),
                    ("BANK_RESERVE_FUND", "Bank - Reserve Fund"),
                    ("BANK_FIXED_DEPOSIT", "Bank - Fixed Deposit"),

                    ("MEMBER_RECEIVABLES", "Member Receivables"),
                    ("VENDOR_PAYABLES", "Vendor Payables"),

                    ("CASH_ON_HAND", "Cash on Hand"),

                    ("MAINTENANCE_INCOME", "Maintenance Income"),
                    ("INTEREST_INCOME", "Interest Income"),
                    ("PENALTY_INCOME", "Penalty Income"),
                    ("PARKING_INCOME", "Parking Income"),
                    ("TRANSFER_FEE_INCOME", "Transfer Fee Income"),
                    ("AMENITY_INCOME", "Amenity Income"),
                    ("RENTAL_INCOME", "Rental Income"),
                    ("MISCELLANEOUS_INCOME", "Miscellaneous Income"),

                    ("MAINTENANCE_EXPENSE", "Maintenance Expense"),
                    ("UTILITY_EXPENSE", "Utility Expense"),
                    ("REPAIR_EXPENSE", "Repair Expense"),
                    ("SECURITY_EXPENSE", "Security Expense"),
                    ("HOUSEKEEPING_EXPENSE", "Housekeeping Expense"),
                    ("ADMINISTRATIVE_EXPENSE", "Administrative Expense"),
                    ("PROFESSIONAL_FEES", "Professional Fees"),
                    ("INSURANCE_EXPENSE", "Insurance Expense"),

                    ("SINKING_FUND", "Sinking Fund"),
                    ("REPAIR_FUND", "Repair Fund"),
                    ("RESERVE_FUND", "Reserve Fund"),
                ],
                help_text=(
                    "Immutable canonical identity used internally "
                    "by SocietyOS financial engines."
                ),
            ),
        ),

        migrations.AlterUniqueTogether(
            name="chartofaccount",
            unique_together={
                ("society", "code"),
                ("society", "system_account"),
            },
        ),

    ]