# Generated by Django 5.2.7 on 2026-07-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("society", "0061_add_system_account_identity_to_chart_of_accounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chartofaccount",
            name="account_type",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("ASSET", "Asset"),
                    ("LIABILITY", "Liability"),
                    ("EQUITY", "Equity"),
                    ("INCOME", "Income"),
                    ("EXPENSE", "Expense"),
                ],
            ),
        ),
    ]