# Generated by Django 5.2.7 on 2026-07-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("society", "0062_introduce_equity_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartofaccount",
            name="equity_type",
            field=models.CharField(
                max_length=50,
                choices=[
                    ("SHARE_CAPITAL", "Share Capital"),
                    ("SHARE_PREMIUM", "Share Premium"),

                    ("STATUTORY_RESERVE", "Statutory Reserve"),
                    ("GENERAL_RESERVE", "General Reserve"),
                    ("RESERVE_FUND", "Reserve Fund"),
                    ("SINKING_FUND", "Sinking Fund"),
                    ("REPAIR_FUND", "Repair Fund"),
                    ("MAJOR_REPAIR_FUND", "Major Repair Fund"),

                    ("BUILDING_RECONSTRUCTION_FUND", "Building Reconstruction Fund"),
                    ("REDEVELOPMENT_FUND", "Redevelopment Fund"),
                    ("CAPITAL_IMPROVEMENT_FUND", "Capital Improvement Fund"),
                    ("INFRASTRUCTURE_FUND", "Infrastructure Fund"),

                    ("CORPUS_FUND", "Corpus Fund"),
                    ("WELFARE_FUND", "Welfare Fund"),
                    ("CULTURAL_FUND", "Cultural Fund"),
                    ("COMMON_AMENITY_FUND", "Common Amenity Fund"),
                    ("PARKING_DEVELOPMENT_FUND", "Parking Development Fund"),
                    ("SECURITY_DEPOSIT_FUND", "Security Deposit Fund"),

                    ("DISASTER_RELIEF_FUND", "Disaster Relief Fund"),
                    ("EMERGENCY_FUND", "Emergency Fund"),
                    ("INSURANCE_RESERVE", "Insurance Reserve"),
                    ("LEGAL_CONTINGENCY_FUND", "Legal Contingency Fund"),
                    ("LITIGATION_FUND", "Litigation Fund"),

                    ("LIFT_REPLACEMENT_FUND", "Lift Replacement Fund"),
                    ("PAINTING_FUND", "Painting Fund"),
                    ("WATER_SYSTEM_FUND", "Water System Fund"),
                    ("SOLAR_PROJECT_FUND", "Solar Project Fund"),
                    ("FIRE_SAFETY_FUND", "Fire Safety Fund"),
                    ("ELECTRICAL_UPGRADE_FUND", "Electrical Upgrade Fund"),

                    ("ACCUMULATED_SURPLUS", "Accumulated Surplus"),
                    ("RETAINED_EARNINGS", "Retained Earnings"),

                    ("GOVERNMENT_GRANT_RESERVE", "Government Grant Reserve"),
                    ("DONATION_FUND", "Donation Fund"),
                    ("CSR_CAPITAL_FUND", "CSR Capital Fund"),

                    ("PROMOTER_CONTRIBUTION", "Promoter Contribution"),
                    ("BUILDER_CONTRIBUTION", "Builder Contribution"),
                    ("INITIAL_WORKING_CAPITAL", "Initial Working Capital"),
                    ("FORMATION_EXPENSE_RECOVERY", "Formation Expense Recovery"),
                ],
                null=True,
                blank=True,
                help_text=(
                    "Statutory classification for Equity accounts. "
                    "Applicable only when account_type is EQUITY."
                ),
            ),
        ),
    ]