# Generated by Django 5.2.7 on 2026-07-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("society", "0063_add_equity_type_to_chart_of_accounts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_number",
                    models.CharField(
                        help_text="Unique society asset identifier",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CIVIL", "Civil"),
                            ("ELECTRICAL", "Electrical"),
                            ("MECHANICAL", "Mechanical"),
                            ("PLUMBING", "Plumbing"),
                            ("FIRE_SAFETY", "Fire Safety"),
                            ("SECURITY", "Security"),
                            ("IT", "Information Technology"),
                            ("FURNITURE", "Furniture & Fixtures"),
                            ("RECREATIONAL", "Recreational"),
                            ("LANDSCAPING", "Landscaping"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("BUILDER", "Builder Handover"),
                            ("PURCHASED", "Purchased by Society"),
                            ("DONATED", "Donated"),
                            ("TRANSFERRED", "Transferred"),
                            ("OTHER", "Other"),
                        ],
                        default="PURCHASED",
                        max_length=20,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "location_description",
                    models.CharField(
                        blank=True,
                        help_text="Exact physical location within society",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "installed_on",
                    models.DateField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "commissioned_on",
                    models.DateField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "expected_life_years",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("UNDER_REPAIR", "Under Repair"),
                            ("NON_OPERATIONAL", "Non Operational"),
                            ("DISPOSED", "Disposed"),
                        ],
                        default="ACTIVE",
                        max_length=25,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                        ],
                        default="GOOD",
                        max_length=20,
                    ),
                ),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "flat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="society.flat",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="society.floor",
                    ),
                ),
                (
                    "society",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="society.society",
                    ),
                ),
                (
                    "wing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="society.wing",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
                "unique_together": {("society", "asset_number")},
            },
        ),
    ]