# Generated by Django 5.2.7 on 2026-07-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("society", "0064_add_society_asset_management_models"),
    ]

    operations = [

        migrations.CreateModel(

            name="AssetValuation",

            fields=[

                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),

                (
                    "valuation_type",
                    models.CharField(
                        max_length=30,
                        choices=[
                            ("ORIGINAL_COST", "Original Cost"),
                            ("OPENING_BALANCE", "Opening Balance"),
                            ("FAIR_VALUE", "Fair Value"),
                        ],
                    ),
                ),

                (
                    "amount",
                    models.DecimalField(
                        max_digits=14,
                        decimal_places=2,
                    ),
                ),

                (
                    "valuation_date",
                    models.DateField(),
                ),

                (
                    "remarks",
                    models.TextField(
                        blank=True,
                    ),
                ),

                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),

                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuations",
                        to="society.asset",
                    ),
                ),

            ],

            options={
                "ordering": [
                    "-valuation_date",
                    "-id",
                ],
            },

        ),

    ]