# Generated by Django 5.2.7 on 2026-07-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("society", "0065_create_asset_valuation"),
    ]

    operations = [

        migrations.AlterUniqueTogether(

            name="assetvaluation",

            unique_together={
                (
                    "asset",
                    "valuation_type",
                ),
            },

        ),

    ]