# Generated by Django 5.2.7 on 2026-07-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("society", "0066_asset_valuation_unique_constraint"),
    ]

    operations = [

        migrations.AddField(
            model_name="expenseauthorization",
            name="operational_domain_code",
            field=models.CharField(
                max_length=100,
                blank=True,
                null=True,
                help_text=(
                    "Canonical operational domain code "
                    "from the Spend Catalog."
                ),
            ),
        ),

        migrations.AddField(
            model_name="expenseauthorization",
            name="spend_item_code",
            field=models.CharField(
                max_length=100,
                blank=True,
                null=True,
                help_text=(
                    "Canonical spend item code "
                    "from the Spend Catalog."
                ),
            ),
        ),

    ]