# Generated by Django 5.2.7 on 2026-08-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "society",
            "0067_add_spend_classification_to_expense_authorization",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                max_length=100,
                default="UNKNOWN",
                help_text=(
                    "Canonical Asset Operating Model "
                    "definition code."
                ),
            ),
            preserve_default=False,
        ),
    ]