# Generated by Django 5.1.15 on 2026-09-24 16:44

import common.ids
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0003_broadcasts"),
        ("masterdata", "0004_ownershipclaim_terms_alter_ownershipclaim_status"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeBlast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("flats", "Flats"), ("requirement", "Requirement")],
                        max_length=12,
                    ),
                ),
                ("text", models.CharField(max_length=1000)),
                (
                    "items",
                    models.JSONField(
                        default=list,
                        help_text="Trade-level summaries: never flat numbers, owners or customers",
                    ),
                ),
                ("listing_ids", models.JSONField(blank=True, default=list)),
                ("audience", models.JSONField(blank=True, default=dict)),
                ("recipients_total", models.PositiveIntegerField(default=0)),
                ("delivered_in_app", models.PositiveIntegerField(default=0)),
                ("via_whatsapp", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        db_column="broker_org_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="orgs.brokerorg",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crm.requirement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TradeReply",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_name", models.CharField(max_length=160)),
                ("from_phone_enc", models.BinaryField(null=True)),
                ("message", models.CharField(blank=True, max_length=300)),
                (
                    "blast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="trade.tradeblast",
                    ),
                ),
                (
                    "from_org",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orgs.brokerorg",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        db_column="broker_org_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="orgs.brokerorg",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FellowBroker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("firm", models.CharField(blank=True, max_length=160)),
                ("phone_hash", models.CharField(max_length=64)),
                ("phone_enc", models.BinaryField()),
                ("address", models.CharField(blank=True, max_length=300)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        help_text="Office pin, if known",
                        null=True,
                        srid=4326,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=300)),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("import", "Import")],
                        default="manual",
                        max_length=8,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "locality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="masterdata.locality",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        db_column="broker_org_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="orgs.brokerorg",
                    ),
                ),
                (
                    "platform_org",
                    models.ForeignKey(
                        blank=True,
                        help_text="Their firm, if they use Only Broker",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orgs.brokerorg",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "phone_hash"),
                        name="one_fellow_broker_per_phone_per_org",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TradeDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("blast_id", models.UUIDField(db_index=True)),
                ("from_name", models.CharField(max_length=160)),
                ("from_phone_enc", models.BinaryField(null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("flats", "Flats"), ("requirement", "Requirement")],
                        max_length=12,
                    ),
                ),
                ("text", models.CharField(max_length=1000)),
                ("items", models.JSONField(default=list)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reply",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("have_customer", "Have Customer"),
                            ("have_flat", "Have Flat"),
                            ("not_now", "Not Now"),
                        ],
                        default="",
                        max_length=14,
                    ),
                ),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "from_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="orgs.brokerorg",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        db_column="broker_org_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="orgs.brokerorg",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "blast_id"),
                        name="one_delivery_per_blast_per_org",
                    )
                ],
            },
        ),
    ]
