"""
==========================================================
SocietyOS
Vendor Payable Factory
==========================================================

Purpose
-------

Creates a Vendor Payable from a Vendor Bill.

This factory owns Vendor Payable creation.

It does NOT:

• recognize accounting
• post journals
• perform payments
• update outstanding balances
"""

from __future__ import annotations

from society.models import (
    VendorBill,
    VendorPayable,
)


class VendorPayableFactoryError(Exception):
    """
    Raised when a Vendor Payable cannot
    be created.
    """
    pass


def create_vendor_payable(
    *,
    vendor_bill: VendorBill,
) -> VendorPayable:
    """
    Creates the payable generated by a
    booked Vendor Bill.
    """

    return VendorPayable.objects.create(
        society=vendor_bill.society,
        vendor_bill=vendor_bill,
        amount=vendor_bill.amount,
        outstanding_amount=vendor_bill.amount,
    )