# Generated by Django 5.1.15 on 2026-09-24 11:29

import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_row_level_security"),
        ("masterdata", "0004_ownershipclaim_terms_alter_ownershipclaim_status"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("txn_type", models.CharField(default="RENT", max_length=12)),
                ("terms", models.JSONField(blank=True, default=dict)),
                (
                    "allowed_at",
                    models.DateTimeField(
                        help_text="When the owner ticked 'Allow this broker to handle my property'"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.listing",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        db_column="broker_org_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="orgs.brokerorg",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="masterdata.unit",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("state", "pending")),
                        fields=("org", "unit"),
                        name="one_pending_invite_per_org_unit",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OwnerWithdrawal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("active", models.BooleanField(default=True)),
                ("reinstated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ask_note",
                    models.CharField(
                        blank=True,
                        help_text="The broker's request to be added back",
                        max_length=300,
                    ),
                ),
                ("asked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "org",
                    models.ForeignKey(
                        db_column="broker_org_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="orgs.brokerorg",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="masterdata.unit",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("org", "unit"),
                        name="one_active_withdrawal",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UnitMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("document", "Document"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="units/%Y/%m/")),
                ("thumb", models.FileField(blank=True, upload_to="units/%Y/%m/")),
                ("content_type", models.CharField(max_length=60)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("caption", models.CharField(blank=True, max_length=120)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media",
                        to="masterdata.ownershipclaim",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="masterdata.unit",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["unit", "kind"], name="owners_unit_unit_id_33699d_idx"
                    )
                ],
            },
        ),
    ]
