# Generated by Django 5.1.15 on 2026-09-24 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0001_initial"),
        ("owners", "0002_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitmedia",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unitmedia",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("live", "Live"),
                    ("rejected", "Rejected"),
                ],
                default="live",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="unitmedia",
            name="uploaded_by_org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="orgs.brokerorg",
            ),
        ),
    ]
