# Generated by Django 5.1.15 on 2026-09-23 19:51

import common.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_hash",
                    models.CharField(
                        blank=True,
                        help_text="For people without an account",
                        max_length=64,
                    ),
                ),
                ("template", models.CharField(max_length=60)),
                ("channel", models.CharField(default="inapp", max_length=12)),
                ("payload", models.JSONField(default=dict)),
                ("state", models.CharField(default="queued", max_length=12)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("provider_msg_id", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReviewQueueItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(db_index=True, max_length=40)),
                ("ref_type", models.CharField(max_length=60)),
                ("ref_id", models.CharField(max_length=64)),
                ("summary", models.CharField(max_length=300)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "state",
                    models.CharField(db_index=True, default="open", max_length=12),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("status_confirmation", "Status Confirmation"),
                            ("visit_plan", "Visit Plan"),
                            ("shortlist", "Shortlist"),
                            ("review", "Review"),
                            ("consent", "Consent"),
                            ("visit_notice", "Visit Notice"),
                        ],
                        max_length=32,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("target_type", models.CharField(max_length=40)),
                ("target_id", models.UUIDField()),
                ("recipient_phone_hash", models.CharField(blank=True, max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("max_uses", models.PositiveIntegerField(default=1)),
                ("uses", models.PositiveIntegerField(default=0)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="DomainEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=80)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["processed_at", "id"], name="outbox_pending_idx"
                    )
                ],
            },
        ),
    ]
