# Generated by Django 5.2.7 on 2026-02-18 20:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforcement_mode', models.CharField(choices=[('OBSERVE_ONLY', 'Observe Only'), ('PROGRESSIVE', 'Progressive'), ('STRICT', 'Strict')], default='OBSERVE_ONLY', max_length=20)),
                ('policy_engine_enabled', models.BooleanField(default=True)),
                ('simulation_enabled', models.BooleanField(default=True)),
                ('rollback_enabled', models.BooleanField(default=True)),
                ('audit_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Governance Control',
            },
        ),
        migrations.CreateModel(
            name='PolicyDecisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_code', models.CharField(max_length=100)),
                ('policy_version', models.PositiveIntegerField()),
                ('actor_id', models.UUIDField()),
                ('action', models.CharField(max_length=100)),
                ('resource', models.CharField(max_length=255)),
                ('decision', models.CharField(max_length=10)),
                ('reason', models.TextField()),
                ('decision_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('scope', models.CharField(max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effect', models.CharField(choices=[('ALLOW', 'ALLOW'), ('DENY', 'DENY'), ('SOFT_DENY', 'SOFT_DENY'), ('OBSERVE', 'OBSERVE')], max_length=10)),
                ('condition', models.JSONField()),
                ('priority', models.PositiveIntegerField(default=100)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='governance.policy')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('society_id', models.UUIDField(blank=True, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='governance.policy')),
            ],
            options={
                'unique_together': {('policy', 'role', 'user_id', 'society_id')},
            },
        ),
    ]
