# Generated by Django 5.2.7 on 2026-01-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='policy',
            unique_together={('code', 'version')},
        ),
    ]
