# Generated by Django 5.2.7 on 2026-01-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_alter_policy_code_alter_policy_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforcement_mode', models.CharField(choices=[('OBSERVE_ONLY', 'Observe Only'), ('PROGRESSIVE', 'Progressive'), ('STRICT', 'Strict')], default='OBSERVE_ONLY', max_length=20)),
                ('policy_engine_enabled', models.BooleanField(default=True)),
                ('simulation_enabled', models.BooleanField(default=True)),
                ('rollback_enabled', models.BooleanField(default=True)),
                ('audit_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Governance Control',
            },
        ),
    ]
