# Generated by Django 5.2.7 on 2026-01-05 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0005_flat_flatownership_flatowner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatowner',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Linked user account (if individual)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='flatownership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('flat',), name='one_active_ownership_per_flat'),
        ),
    ]
