# Generated by Django 5.2.7 on 2026-01-05 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0006_alter_flatowner_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_chargeable', models.BooleanField(default=False)),
                ('charge_type', models.CharField(blank=True, choices=[('PER_USE', 'Per Use'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='society.society')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('society', 'name')},
            },
        ),
    ]
