# Generated by Django 5.2.7 on 2026-01-06 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0008_parkingslot_parkingallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='charge_type',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='is_chargeable',
        ),
        migrations.AddField(
            model_name='amenity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amenity',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='Mandatory for all flats'),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='slot_number',
            field=models.CharField(max_length=20),
        ),
    ]
