# Generated by Django 5.2.7 on 2026-01-06 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0011_flatoccupancy_maintenanceaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_percentage', models.BooleanField(default=False, help_text='If true, charge is a percentage-based calculation')),
                ('max_percentage_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed percentage (e.g. 10.00 for NOC)', max_digits=5, null=True)),
                ('applies_on', models.CharField(choices=[('SERVICE_CHARGES', 'Service Charges'), ('MAINTENANCE', 'Maintenance'), ('NONE', 'Not Applicable')], default='NONE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='maintenanceaccount',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='maintenanceaccount',
            name='is_defaulter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenanceaccount',
            name='last_billed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SocietyChargeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percentage or flat amount depending on charge type', max_digits=8)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='society.chargetype')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_rules', to='society.society')),
            ],
            options={
                'unique_together': {('society', 'charge_type', 'effective_from')},
            },
        ),
    ]
