# Generated by Django 5.2.7 on 2026-01-08 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0017_societyrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(choices=[('REMINDER', 'Reminder'), ('DEMAND', 'Demand Notice'), ('FINAL', 'Final Notice')], max_length=20)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('generated_on', models.DateField(auto_now_add=True)),
                ('reference_period', models.CharField(help_text='E.g. Jan 2026 – Mar 2026', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='society.flat')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='society.society')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
