# Generated by Django 5.2.7 on 2026-01-09 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0021_flatrecoverystatus_recoveryactionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='date_of_registration',
        ),
        migrations.RemoveField(
            model_name='society',
            name='registration_no',
        ),
        migrations.AddField(
            model_name='society',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='society',
            name='registrar_office',
            field=models.CharField(blank=True, help_text='Registrar office / ward / zone', max_length=255),
        ),
        migrations.AddField(
            model_name='society',
            name='registration_date',
            field=models.DateField(blank=True, help_text='Date of registration with Registrar', null=True),
        ),
        migrations.AddField(
            model_name='society',
            name='registration_number',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, help_text='Official society registration number issued by Registrar', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='society',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='society',
            constraint=models.UniqueConstraint(fields=('registration_number',), name='unique_society_registration_number'),
        ),
    ]
