# Generated by Django 5.2.7 on 2026-01-09 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0022_remove_society_date_of_registration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short account code (e.g. MAINT, BANK, SINKFUND)', max_length=20)),
                ('name', models.CharField(help_text='Account name (e.g. Maintenance Charges)', max_length=255)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('EQUITY', 'Equity')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_of_accounts', to='society.society')),
            ],
            options={
                'ordering': ['account_type', 'code'],
                'unique_together': {('society', 'code')},
            },
        ),
    ]
