from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.http import JsonResponse
import os

@api_view(["POST"])
def upload_signed_bylaws(request):
    society_id = request.data.get("society_id")
    file = request.FILES.get("file")

    if not society_id or not file:
        return Response({"error": "Missing data"}, status=400)

    from society.models import Society
    society = Society.objects.get(id=society_id)

    base_dir = "/tmp/bylaws"
    society_name = society.name.replace(" ", "_")

    society_path = os.path.join(base_dir, society_name)

    if not os.path.exists(society_path):
        return Response({"error": "No generated bylaws found"}, status=404)

    # 🔥 GET LATEST VERSION
    versions = sorted(os.listdir(society_path), reverse=True)
    latest_version = versions[0]

    version_path = os.path.join(society_path, latest_version)

    # 🔥 SAVE SIGNED FILE
    signed_path = os.path.join(version_path, "signed_copy.pdf")

    with open(signed_path, "wb+") as destination:
        for chunk in file.chunks():
            destination.write(chunk)

    from statutory.models import SocietyBylaws

    doc = SocietyBylaws.objects.filter(
        society=society
    ).order_by("-version_number").first()

    if doc:
        doc.signed_document_path = signed_path
        doc.status = "SIGNED"
        doc.save()
        
    return JsonResponse({
        "status": "success",
        "message": "Signed bylaws uploaded",
        "path": signed_path
    })