# Generated by Django 5.1.15 on 2026-09-23 19:51

import common.ids
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0002_initial"),
        ("inventory", "0001_initial"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncMutation",
            fields=[
                (
                    "idempotency_key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("device_id", models.CharField(max_length=64)),
                ("entity", models.CharField(max_length=30)),
                ("payload", models.JSONField()),
                ("client_ts", models.DateTimeField()),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("result", models.CharField(max_length=10)),
                ("detail", models.JSONField(default=dict)),
                (
                    "org",
                    models.ForeignKey(
                        db_column="broker_org_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="orgs.brokerorg",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                (
                    "start_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "travel_mode",
                    models.CharField(
                        choices=[
                            ("drive", "Drive"),
                            ("two_wheeler", "Two Wheeler"),
                            ("walk", "Walk"),
                        ],
                        default="two_wheeler",
                        max_length=12,
                    ),
                ),
                ("dwell_min", models.PositiveSmallIntegerField(default=15)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("shared", "Shared"),
                            ("customer_confirmed", "Customer Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("customer_proposed_slot", models.DateTimeField(blank=True, null=True)),
                ("route_method", models.CharField(blank=True, max_length=20)),
                (
                    "total_travel_min",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_plans",
                        to="crm.customer",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        db_column="broker_org_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="orgs.brokerorg",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crm.requirement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VisitStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seq", models.PositiveSmallIntegerField()),
                ("slot_start", models.DateTimeField(blank=True, null=True)),
                ("slot_end", models.DateTimeField(blank=True, null=True)),
                ("staff_ack_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner_notice",
                    models.CharField(
                        choices=[
                            ("not_required", "Not Required"),
                            ("sent", "Sent"),
                            ("acknowledged", "Acknowledged"),
                            ("declined", "Declined"),
                        ],
                        default="not_required",
                        max_length=14,
                    ),
                ),
                ("checkin_at", models.DateTimeField(blank=True, null=True)),
                ("checkout_at", models.DateTimeField(blank=True, null=True)),
                (
                    "checkin_distance_m",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("liked", "Liked"),
                            ("rejected", "Rejected"),
                            ("shortlisted", "Shortlisted"),
                            ("second_visit", "Second Visit"),
                            ("no_show", "No Show"),
                            ("not_accessible", "Not Accessible"),
                            ("already_let", "Already Let"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reject_reasons", models.JSONField(blank=True, default=list)),
                ("feedback_note", models.CharField(blank=True, max_length=500)),
                ("removed", models.BooleanField(default=False)),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.listing",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        db_column="broker_org_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="orgs.brokerorg",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="visits.visitplan",
                    ),
                ),
            ],
            options={
                "ordering": ["seq"],
            },
        ),
    ]
