# Generated by Django 5.1.15 on 2026-09-23 19:51

import common.ids
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("visit_completed", "Visit Completed"),
                            ("deal_closed", "Deal Closed"),
                            ("owner_representation", "Owner Representation"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "customer_phone_hash",
                    models.CharField(
                        blank=True,
                        help_text="Offline customers (OFF-08)",
                        max_length=64,
                    ),
                ),
                ("ref_type", models.CharField(max_length=40)),
                ("ref_id", models.UUIDField()),
                ("occurred_at", models.DateTimeField()),
                (
                    "customer_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="orgs.brokerorg",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("C2B", "C2B"),
                            ("B2C", "B2C"),
                            ("O2B", "O2B"),
                            ("B2O", "B2O"),
                            ("C2U", "C2U"),
                        ],
                        max_length=3,
                    ),
                ),
                ("reviewer_label", models.CharField(blank=True, max_length=60)),
                ("stars", models.PositiveSmallIntegerField()),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=1000)),
                (
                    "moderation_state",
                    models.CharField(default="published", max_length=10),
                ),
                ("reply_text", models.CharField(blank=True, max_length=1000)),
                ("verified_offline", models.BooleanField(default=False)),
                (
                    "interaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="reviews.interaction",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="orgs.brokerorg",
                    ),
                ),
                (
                    "reviewee_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="interaction",
            constraint=models.UniqueConstraint(
                fields=("kind", "ref_type", "ref_id"), name="one_interaction_per_ref"
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("interaction", "direction"),
                name="one_review_per_interaction_direction",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(("stars__gte", 1), ("stars__lte", 5)),
                name="stars_1_5",
            ),
        ),
    ]
