# Generated by Django 5.1.15 on 2026-09-23 19:51

import common.ids
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttributeDef",
            fields=[
                (
                    "key",
                    models.SlugField(max_length=60, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=120)),
                ("label_i18n", models.JSONField(blank=True, default=dict)),
                ("category", models.CharField(max_length=60)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("unit", "Unit"),
                            ("building", "Building"),
                            ("society", "Society"),
                            ("listing", "Listing"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("bool", "Bool"),
                            ("enum", "Enum"),
                            ("multi_enum", "Multi Enum"),
                            ("int", "Int"),
                            ("numeric", "Numeric"),
                            ("money", "Money"),
                            ("date", "Date"),
                            ("text", "Text"),
                            ("ref", "Ref"),
                        ],
                        max_length=12,
                    ),
                ),
                ("allowed_values", models.JSONField(blank=True, default=list)),
                ("unit_label", models.CharField(blank=True, max_length=40)),
                (
                    "authority",
                    models.CharField(
                        choices=[
                            ("computed", "Computed"),
                            ("owner", "Owner"),
                            ("any", "Any"),
                            ("admin", "Admin"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "matching",
                    models.CharField(
                        choices=[
                            ("hard", "Hard"),
                            ("soft", "Soft"),
                            ("display", "Display"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "public",
                    models.CharField(
                        default="Y", help_text="Y, N or Band", max_length=4
                    ),
                ),
                (
                    "applies_to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=12),
                        default=list,
                        size=None,
                    ),
                ),
                ("mvp", models.BooleanField(default=False)),
                (
                    "entry_tier",
                    models.CharField(
                        default="detailed",
                        help_text="essential | recommended | detailed | system",
                        max_length=12,
                    ),
                ),
                (
                    "asked_of",
                    models.CharField(
                        default="broker",
                        help_text="broker | owner | building | nobody",
                        max_length=12,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("dictionary_version", models.CharField(default="", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='"A Wing", "Tower 3"; "Main" when the society is one building',
                        max_length=80,
                    ),
                ),
                ("name_normalised", models.CharField(max_length=80)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "floors_total",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("lifts", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("year_built", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Locality",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("name_normalised", models.CharField(db_index=True, max_length=80)),
                (
                    "pincodes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=6),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "localities",
            },
        ),
        migrations.CreateModel(
            name="LocationFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "poi_type",
                    models.CharField(
                        choices=[
                            ("rail_station", "Rail Station"),
                            ("metro_station", "Metro Station"),
                            ("metro_upcoming", "Metro Upcoming"),
                            ("bus_stop", "Bus Stop"),
                            ("auto_stand", "Auto Stand"),
                            ("school", "School"),
                            ("hospital", "Hospital"),
                            ("market", "Market"),
                            ("mall", "Mall"),
                            ("park", "Park"),
                            ("highway", "Highway"),
                            ("atm_bank", "Atm Bank"),
                            ("pharmacy", "Pharmacy"),
                            ("police_station", "Police Station"),
                        ],
                        max_length=20,
                    ),
                ),
                ("poi_name", models.CharField(max_length=160)),
                ("distance_m", models.PositiveIntegerField()),
                ("walk_min", models.PositiveSmallIntegerField()),
                ("drive_min", models.PositiveSmallIntegerField()),
                (
                    "method",
                    models.CharField(
                        default="estimate",
                        help_text="estimate | routes_api",
                        max_length=12,
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MicroMarket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("city", models.CharField(default="MMR", max_length=40)),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "launch_state",
                    models.CharField(
                        choices=[("off", "Off"), ("pilot", "Pilot"), ("live", "Live")],
                        default="off",
                        max_length=5,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OwnershipClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("proof_type", models.CharField(blank=True, max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Poi",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("rail_station", "Rail Station"),
                            ("metro_station", "Metro Station"),
                            ("metro_upcoming", "Metro Upcoming"),
                            ("bus_stop", "Bus Stop"),
                            ("auto_stand", "Auto Stand"),
                            ("school", "School"),
                            ("hospital", "Hospital"),
                            ("market", "Market"),
                            ("mall", "Mall"),
                            ("park", "Park"),
                            ("highway", "Highway"),
                            ("atm_bank", "Atm Bank"),
                            ("pharmacy", "Pharmacy"),
                            ("police_station", "Police Station"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("source", models.CharField(default="osm", max_length=20)),
                ("verified", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResolvedAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("unit", "Unit"),
                            ("building", "Building"),
                            ("society", "Society"),
                            ("listing", "Listing"),
                        ],
                        max_length=10,
                    ),
                ),
                ("subject_id", models.UUIDField()),
                ("value", models.JSONField()),
                ("resolved_source_type", models.CharField(max_length=20)),
                ("support", models.PositiveIntegerField(default=1)),
                ("disputed", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Society",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("canonical_name", models.CharField(max_length=200)),
                ("name_normalised", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("chs", "Chs"),
                            ("project", "Project"),
                            ("standalone_building", "Standalone"),
                            ("layout", "Layout"),
                        ],
                        default="chs",
                        max_length=20,
                    ),
                ),
                ("address_line", models.CharField(blank=True, max_length=300)),
                ("pincode", models.CharField(blank=True, max_length=6)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "rera_project_nos",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("possession_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisional", "Provisional"),
                            ("active", "Active"),
                            ("merged", "Merged"),
                            ("rejected", "Rejected"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("provenance", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name_plural": "societies",
            },
        ),
        migrations.CreateModel(
            name="SocietyAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alias_raw", models.CharField(max_length=200)),
                ("alias_normalised", models.CharField(max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("seed", "Seed"),
                            ("canonical", "Canonical"),
                            ("broker_upload", "Broker Upload"),
                            ("broker_confirmed", "Broker Confirmed"),
                            ("admin", "Admin"),
                            ("merge", "Merge"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confirmations", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("unit_no", models.CharField(max_length=30)),
                ("unit_no_normalised", models.CharField(max_length=30)),
                ("floor", models.SmallIntegerField(blank=True, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        help_text="Defaults to building; override ≤ 150 m",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("row_house", "Row House"),
                            ("independent_house", "Independent House"),
                            ("villa", "Villa"),
                            ("penthouse", "Penthouse"),
                            ("studio", "Studio"),
                        ],
                        default="apartment",
                        max_length=20,
                    ),
                ),
                (
                    "bhk",
                    models.DecimalField(
                        decimal_places=1, help_text="0.5 = 1RK", max_digits=3
                    ),
                ),
                (
                    "carpet_sqft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttributeObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("unit", "Unit"),
                            ("building", "Building"),
                            ("society", "Society"),
                            ("listing", "Listing"),
                        ],
                        max_length=10,
                    ),
                ),
                ("subject_id", models.UUIDField()),
                ("value", models.JSONField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("computed", "Computed"),
                            ("owner_verified", "Owner Verified"),
                            ("admin", "Admin"),
                            ("visit_feedback", "Visit Feedback"),
                            ("broker", "Broker"),
                            ("upload", "Upload"),
                            ("customer", "Customer"),
                            ("owner_via_broker", "Owner Via Broker"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(decimal_places=2, default=1, max_digits=3),
                ),
                ("observed_at", models.DateTimeField()),
                (
                    "attr",
                    models.ForeignKey(
                        db_column="attr_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="masterdata.attributedef",
                    ),
                ),
            ],
        ),
    ]
