# Generated by Django 5.1.15 on 2026-09-23 19:51

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masterdata", "0001_initial"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attributeobservation",
            name="source_org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="orgs.brokerorg",
            ),
        ),
        migrations.AddField(
            model_name="attributeobservation",
            name="source_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="masterdata.building",
            ),
        ),
        migrations.AddField(
            model_name="locationfact",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_facts",
                to="masterdata.building",
            ),
        ),
        migrations.AddField(
            model_name="locality",
            name="micro_market",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="localities",
                to="masterdata.micromarket",
            ),
        ),
        migrations.AddField(
            model_name="ownershipclaim",
            name="attested_by_org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="orgs.brokerorg",
            ),
        ),
        migrations.AddField(
            model_name="ownershipclaim",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownership_claims",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="locationfact",
            name="poi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="masterdata.poi"
            ),
        ),
        migrations.AddField(
            model_name="resolvedattribute",
            name="attr",
            field=models.ForeignKey(
                db_column="attr_key",
                on_delete=django.db.models.deletion.PROTECT,
                to="masterdata.attributedef",
            ),
        ),
        migrations.AddField(
            model_name="society",
            name="locality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="societies",
                to="masterdata.locality",
            ),
        ),
        migrations.AddField(
            model_name="society",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="masterdata.society",
            ),
        ),
        migrations.AddField(
            model_name="society",
            name="proposed_by_org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="orgs.brokerorg",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="society",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="buildings",
                to="masterdata.society",
            ),
        ),
        migrations.AddField(
            model_name="societyalias",
            name="created_by_org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="orgs.brokerorg",
            ),
        ),
        migrations.AddField(
            model_name="societyalias",
            name="society",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="masterdata.society",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="units",
                to="masterdata.building",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="masterdata.unit",
            ),
        ),
        migrations.AddField(
            model_name="ownershipclaim",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownership_claims",
                to="masterdata.unit",
            ),
        ),
        migrations.AddIndex(
            model_name="attributeobservation",
            index=models.Index(
                fields=["subject_type", "subject_id", "attr"],
                name="masterdata__subject_43d9b3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="locality",
            constraint=models.UniqueConstraint(
                fields=("micro_market", "name"), name="uniq_locality_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="locationfact",
            constraint=models.UniqueConstraint(
                fields=("building", "poi_type"), name="uniq_fact"
            ),
        ),
        migrations.AddIndex(
            model_name="resolvedattribute",
            index=models.Index(
                fields=["attr", "subject_type"], name="masterdata__attr_ke_cbccf2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="resolvedattribute",
            constraint=models.UniqueConstraint(
                fields=("subject_type", "subject_id", "attr"), name="uniq_resolved"
            ),
        ),
        migrations.AddIndex(
            model_name="society",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_normalised"],
                name="society_name_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="building",
            constraint=models.UniqueConstraint(
                condition=models.Q(("merged_into__isnull", True)),
                fields=("society", "name_normalised"),
                name="uniq_building",
            ),
        ),
        migrations.AddIndex(
            model_name="societyalias",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["alias_normalised"],
                name="alias_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="societyalias",
            constraint=models.UniqueConstraint(
                fields=("alias_normalised", "society"), name="uniq_alias"
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("merged_into__isnull", True)),
                fields=("building", "unit_no_normalised"),
                name="uniq_unit",
            ),
        ),
    ]
