# Generated by Django 5.1.15 on 2026-09-24 10:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="extra_unit_nos",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=30),
                blank=True,
                default=list,
                help_text="Real flats outside the pattern: penthouses, 1203A",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="layout_source",
            field=models.CharField(
                blank=True,
                help_text="rera | survey | broker | ops | demo",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="layout_verified",
            field=models.BooleanField(
                default=False,
                help_text="Verified layouts block impossible flat numbers",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="lowest_floor",
            field=models.SmallIntegerField(
                default=1,
                help_text="First floor with flats: 0 = ground, 1 = above stilt parking",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="skip_floors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.SmallIntegerField(),
                blank=True,
                default=list,
                help_text="Refuge / podium floors with no flats",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="units_per_floor",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Flats per typical floor (01..N)", null=True
            ),
        ),
        migrations.AddField(
            model_name="society",
            name="wings_complete",
            field=models.BooleanField(
                default=False,
                help_text="Every wing is on record: an unknown wing name is a typo, never a new building",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="floors_total",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Highest residential floor", null=True
            ),
        ),
    ]
