# Generated by Django 5.1.15 on 2026-09-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0003_building_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownershipclaim",
            name="terms",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Owner's preferred terms: rent/price, deposit, available from",
            ),
        ),
        migrations.AlterField(
            model_name="ownershipclaim",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("declared", "Declared"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("revoked", "Revoked"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
