# Generated by Django 5.1.15 on 2026-09-24 16:47

import common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0004_ownershipclaim_terms_alter_ownershipclaim_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="register_complete",
            field=models.BooleanField(
                default=False,
                help_text="Every flat of this wing is in RegisterFlat (official list): other flat numbers cannot exist",
            ),
        ),
        migrations.CreateModel(
            name="RegisterFlat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("unit_no", models.CharField(max_length=30)),
                ("unit_no_normalised", models.CharField(max_length=30)),
                ("floor", models.SmallIntegerField(blank=True, null=True)),
                (
                    "carpet_sqft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("tmc", "TMC property tax"),
                            ("rera", "MahaRERA"),
                            ("igr", "IGR registrations"),
                            ("ops", "Ops (from an official document)"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True, help_text="e.g. TMC property number", max_length=40
                    ),
                ),
                ("ward", models.CharField(blank=True, max_length=40)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="register_flats",
                        to="masterdata.building",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("building", "unit_no_normalised"),
                        name="uniq_register_flat",
                    )
                ],
            },
        ),
    ]
