# Generated by Django 5.2.7 on 2026-02-19 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BylawChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('sequence_order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='BylawDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_code', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('IDENTITY', 'Identity'), ('MEMBERSHIP', 'Membership'), ('SHARE_CAPITAL', 'Share Capital'), ('COMMITTEE', 'Committee Structure'), ('FINANCE', 'Finance'), ('USAGE', 'Usage'), ('TENANCY', 'Tenancy'), ('TRANSFER', 'Transfer'), ('COMPLIANCE', 'Compliance'), ('DISCIPLINE', 'Discipline')], max_length=40)),
                ('question', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('legal_reference', models.TextField(blank=True)),
                ('allowed_values', models.JSONField(blank=True, default=dict)),
                ('default_value', models.JSONField(blank=True, default=dict)),
                ('risk_rules', models.JSONField(blank=True, default=dict)),
                ('registrar_notes', models.TextField(blank=True)),
                ('clause_template_code', models.CharField(blank=True, max_length=120)),
                ('sequence_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BylawVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BylawClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clause_number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('legal_text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('machine_tags', models.JSONField(blank=True, default=dict)),
                ('sequence_order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='bylaws.bylawchapter')),
            ],
            options={
                'ordering': ['sequence_order'],
                'unique_together': {('chapter', 'clause_number')},
            },
        ),
        migrations.CreateModel(
            name='BylawDecisionHook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_code', models.CharField(max_length=100)),
                ('enforcement_level', models.CharField(choices=[('INFO', 'Informational'), ('ADVISORY', 'Advisory'), ('SOFT_BLOCK', 'Soft Block'), ('HARD_BLOCK', 'Hard Block')], default='ADVISORY', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_hooks', to='bylaws.bylawclause')),
            ],
        ),
        migrations.CreateModel(
            name='BylawDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.CharField(default='MH-2014', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('approved_by_committee', models.BooleanField(default=False)),
                ('registrar_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='society.case')),
            ],
        ),
        migrations.CreateModel(
            name='BylawDraftDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_key', models.CharField(max_length=100)),
                ('decision_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bylaws.bylawdraft')),
            ],
        ),
        migrations.AddField(
            model_name='bylawchapter',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='bylaws.bylawversion'),
        ),
        migrations.CreateModel(
            name='BylawSubClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_clause_number', models.CharField(max_length=10)),
                ('legal_text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('sequence_order', models.PositiveIntegerField()),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_clauses', to='bylaws.bylawclause')),
            ],
            options={
                'ordering': ['sequence_order'],
                'unique_together': {('clause', 'sub_clause_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bylawchapter',
            unique_together={('version', 'chapter_number')},
        ),
        migrations.CreateModel(
            name='DecisionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='bylaws.bylawdecision')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_sessions', to='bylaws.bylawdraft')),
            ],
            options={
                'unique_together': {('draft', 'decision')},
            },
        ),
    ]
