# Generated by Django 5.2.7 on 2026-02-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bylaws', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bylawchapter',
            table='statutory_bylawchapter',
        ),
        migrations.AlterModelTable(
            name='bylawclause',
            table='statutory_bylawclause',
        ),
        migrations.AlterModelTable(
            name='bylawdecision',
            table='statutory_bylawdecision',
        ),
        migrations.AlterModelTable(
            name='bylawdecisionhook',
            table='statutory_bylawdecisionhook',
        ),
        migrations.AlterModelTable(
            name='bylawdraft',
            table='statutory_bylawdraft',
        ),
        migrations.AlterModelTable(
            name='bylawdraftdecision',
            table='statutory_bylawdraftdecision',
        ),
        migrations.AlterModelTable(
            name='bylawsubclause',
            table='statutory_bylawsubclause',
        ),
        migrations.AlterModelTable(
            name='bylawversion',
            table='statutory_bylawversion',
        ),
        migrations.AlterModelTable(
            name='decisionsession',
            table='statutory_decisionsession',
        ),
    ]
